In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [1]:
# install library
!pip -q install econci

In [2]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import econci

load Atlas data

In [ ]:
root_folder = "/content/drive/MyDrive/Auto Research Team Folder/Trade reconciliation/Trade  data/ATLAS DATA"
file_name= "atlas_data.csv"
atlas_data = pd.read_csv(f'{root_folder}/{file_name}',dtype = {'HS4_code':str})
# drop unncessary columns
atlas_data = atlas_data.drop(columns=['pci', 'eci', 'coi', 'country_id', 'partner_country_id'])

In [ ]:
atlas_2022 = atlas_data[atlas_data['year'] == 2022]
atlas_2022.reset_index(drop=True, inplace=True)

Load BACI Trade data

In [4]:
root_folder = "/content/drive/MyDrive/Auto Research Team Folder/Trade reconciliation//Reconciled data"
file_name= "Baci_2021.csv"
Baci_2021 = pd.read_csv(f'{root_folder}/{file_name}',dtype = {'H0':str ,'HS4_code':str})
# RANAME COLUMN NAME
#Baci_2022.rename(columns={'cmdCode': 'H0'}, inplace=True)
Baci_2021.reset_index(drop=True, inplace=True)

Load Tji dataframe

In [5]:
root_folder = "/content/drive/MyDrive/Auto Research Team Folder/Trade reconciliation/Reconciled data"
file_name= "reconciled1_trade_2021.csv"
trade_df = pd.read_csv(f'{root_folder}/{file_name}',dtype = {'H0':str ,'HS4_code':str})

In [6]:
trade_df.reset_index(drop=True, inplace=True)

In [7]:
# Remove rows where reconciled_value_trade is 0
trade_df = trade_df[trade_df['reconciled_value'] != 0]

In [8]:
trade_df.head()

   period HS4_code      H0 exporterISO importerISO  reconciled_value
0    2021     0101  010111         MUS         FRA           13720.0
1    2021     0101  010111         ISL         ITA            3963.0
2    2021     0101  010111         PAN         USA          102153.0
3    2021     0101  010111         NLD         SVN           27402.0
4    2021     0101  010111         SVK         IRL            6491.0

In [9]:
Baci_2021.head()

,HS4_code,H0,period,reconciled_value,exporter,exporterISO,importer,importerISO
0,4202,420229,2021,598.0,Afghanistan,AFG,Andorra,AND
1,6210,621050,2021,200.0,Afghanistan,AFG,Andorra,AND
2,6403,640319,2021,167.0,Afghanistan,AFG,Andorra,AND
3,8708,870899,2021,461.0,Afghanistan,AFG,Andorra,AND
4,3823,382390,2021,53029.0,Afghanistan,AFG,Angola,AGO

In [ ]:
atlas_2022.head()

,year,HS4_code,export_value,import_value,exporterISO,exporter,importerISO,importer
0,2022,710,32665.0,0.0,AFG,Afghanistan,AGO,Angola
1,2022,710,1686.0,0.0,AFG,Afghanistan,AUS,Australia
2,2022,710,19977.0,0.0,AFG,Afghanistan,AUT,Austria
3,2022,710,73657.0,0.0,AFG,Afghanistan,CAN,Canada
4,2022,710,0.0,6979.0,AFG,Afghanistan,NaN,NaN

DIFFERENCES

In [10]:
print(trade_df.shape)
print(Baci_2021.shape)
#print(atlas_2022.shape)

(10073640, 6)
(11040285, 8)

In [11]:
total_export_value = Baci_2021['reconciled_value'].sum()
print(f"Total Export Value: {total_export_value}")

Total Export Value: 21116050801892.0

In [12]:
total_export_value = trade_df['reconciled_value'].sum()
print(f"Total Export Value: {total_export_value}")

Total Export Value: 21214670236947.0

In [ ]:
total_export_value = atlas_2022['export_value'].sum()
print(f"Total Export Value: {total_export_value}")

Total Export Value: 23671454893990.0

In [13]:
print(trade_df['exporterISO'].nunique())
print(trade_df['importerISO'].nunique())
print(trade_df['H0'].nunique())
print(trade_df['HS4_code'].nunique())

226
226
4643
1217

In [14]:
print(Baci_2021['exporterISO'].nunique())
print(Baci_2021['importerISO'].nunique())
print(Baci_2021['H0'].nunique())
print(Baci_2021['HS4_code'].nunique())

226
226
4643
1217

In [ ]:
print(atlas_data['exporter'].nunique())
print(atlas_data['importer'].nunique())
print(atlas_data['HS4_code'].nunique())

221
221
1220

In [ ]:
# Group by exporter and sum the reconciled value
exporter_atlas_value = atlas_2022.groupby('exporter')['export_value'].sum()
exporter_atlas_value.sort_values(ascending=False).reset_index().head(20)

In [16]:
# Group by exporter and sum the reconciled value
exporter_reconciled_value = trade_df.groupby('exporterISO')['reconciled_value'].sum()
exporter_reconciled_value.sort_values(ascending=False).reset_index().head(20)

   exporterISO  reconciled_value
0          CHN      3.202492e+12
1          USA      1.724198e+12
2          DEU      1.533451e+12
3          JPN      7.464638e+11
4          KOR      6.452291e+11
5          NLD      6.428634e+11
6          ITA      5.970514e+11
7          FRA      5.620527e+11
8          RUS      5.055322e+11
9          CAN      4.816533e+11
10         MEX      4.759109e+11
11         S19      4.683907e+11
12         BEL      4.265313e+11
13         GBR      4.240125e+11
14         IND      3.974156e+11
15         SGP      3.764404e+11
16         ESP      3.647951e+11
17         VNM      3.645756e+11
18         AUS      3.634956e+11
19         CHE      3.632513e+11

In [17]:
# Group by exporter and sum the reconciled value
exporter_reconciled_value = Baci_2021.groupby('exporterISO')['reconciled_value'].sum()
exporter_reconciled_value.sort_values(ascending=False).reset_index().head(20)

   exporterISO  reconciled_value
0          CHN      3.319573e+12
1          USA      1.643171e+12
2          DEU      1.560253e+12
3          JPN      7.358046e+11
4          KOR      6.575186e+11
5          NLD      6.399811e+11
6          ITA      5.951708e+11
7          FRA      5.696683e+11
8          CAN      4.857302e+11
9          RUS      4.837251e+11
10         S19      4.813630e+11
11         MEX      4.782353e+11
12         GBR      4.219341e+11
13         IND      4.042470e+11
14         BEL      4.034417e+11
15         CHE      3.725484e+11
16         ESP      3.720079e+11
17         VNM      3.558232e+11
18         SGP      3.501084e+11
19         AUS      3.480802e+11

In [18]:
# Create DataFrames for both datasets
df_trade = trade_df.groupby('exporterISO')['reconciled_value'].sum().reset_index()
df_baci = Baci_2021.groupby('exporterISO')['reconciled_value'].sum().reset_index()
#df_atlas = atlas_2022.groupby('exporterISO')['export_value'].sum().reset_index()

In [20]:
# Merge the two DataFrames on 'exporterISO'
merged_export = df_trade.merge(df_baci, on='exporterISO', suffixes=('_trade', '_baci'))

In [21]:
# Create DataFrames for both datasets
df1_trade = trade_df.groupby('importerISO')['reconciled_value'].sum().reset_index()
df1_baci = Baci_2021.groupby('importerISO')['reconciled_value'].sum().reset_index()
#df1_atlas = atlas_2022.groupby('importerISO')['import_value'].sum().reset_index()

In [27]:
# Merge the two DataFrames on 'exporterISO'
merged_import = df1_trade.merge(df1_baci, on='importerISO', suffixes=('_trade', '_baci'))

In [28]:
merged_import.head()

  importerISO  reconciled_value_trade  reconciled_value_baci
0         ABW            1.268885e+09           1.302995e+09
1         AFG            7.335462e+09           7.348640e+09
2         AGO            1.056145e+10           1.126034e+10
3         AIA            2.205599e+08           2.205593e+08
4         ALB            6.810161e+09           6.867054e+09

In [25]:
# Calculate percentage difference
merged_export['percentage_difference'] = ((merged_export['reconciled_value_trade'] - merged_export['reconciled_value_baci']) / merged_export['reconciled_value_baci']) * 100

In [29]:
# Calculate percentage difference
merged_import['percentage_difference'] = ((merged_import['reconciled_value_trade'] - merged_import['reconciled_value_baci']) / merged_import['reconciled_value_baci']) * 100

In [31]:
merged_export.sort_values(by='percentage_difference', ascending =False).reset_index().head(60)

,index,exporterISO,reconciled_value_trade,reconciled_value_baci,percentage_difference
0,57,DJI,3.192624e+09,3.381253e+08,844.213293
1,196,TCA,4.739708e+07,1.436657e+07,229.912314
2,50,CUB,2.162459e+09,1.078710e+09,100.467181
3,44,COG,1.131390e+10,6.541403e+09,72.958307
4,48,CPV,1.893015e+08,1.148377e+08,64.842731
5,88,HKG,1.956951e+11,1.241476e+11,57.631009
6,76,GHA,2.179197e+10,1.465395e+10,48.710533
7,216,VEN,4.805410e+09,3.239193e+09,48.352061
8,107,KGZ,3.242903e+09,2.390641e+09,35.649928
9,210,UGA,5.882470e+09,4.530520e+09,29.840959
10,83,GRD,4.230868e+07,3.349974e+07,26.295562
11,168,PYF,2.169021e+08,1.719102e+08,26.171735
12,224,ZMB,1.523258e+10,1.250968e+10,21.766355
13,11,ATG,2.338644e+08,1.929114e+08,21.228917
14,129,MHL,1.677698e+09,1.404819e+09,19.424494
15,225,ZWE,9.293585e+09,7.861152e+09,18.221671
16,8,ARM,3.976490e+09,3.378983e+09,17.683049
17,49,CRI,1.903446e+10,1.627690e+10,16.941516
18,148,NIC,8.106441e+09,6.978139e+09,16.169099
19,63,EGY,4.992049e+10,4.338504e+10,15.063814
20,205,TTO,1.134746e+10,9.918931e+09,14.402009
21,42,CMR,5.645399e+09,4.970883e+09,13.569355
22,62,ECU,3.084969e+10,2.734289e+10,12.825292
23,127,MDV,2.776802e+08,2.464872e+08,12.655020
24,202,TKM,9.472568e+09,8.431474e+09,12.347708
25,164,PRK,2.557968e+08,2.281630e+08,12.111453
26,180,SLE,9.717107e+08,8.683676e+08,11.900842
27,159,PER,6.358159e+10,5.684692e+10,11.847027
28,58,DMA,4.724473e+07,4.251356e+07,11.128599
29,22,BHR,1.825305e+10,1.652432e+10,10.461764
30,46,COL,4.699312e+10,4.262653e+10,10.243839
31,153,NRU,2.104738e+08,1.911297e+08,10.120901
32,116,LBY,3.279318e+10,2.978480e+10,10.100412
33,23,BHS,1.552390e+09,1.411438e+09,9.986381
34,61,DZA,3.844690e+10,3.499666e+10,9.858780
35,81,GNQ,5.232763e+09,4.764054e+09,9.838451
36,179,SLB,5.340931e+08,4.872083e+08,9.623157
37,72,FSM,1.991789e+08,1.817472e+08,9.591173
38,212,URY,1.173325e+10,1.072327e+10,9.418646
39,17,BEN,2.388487e+09,2.193570e+09,8.885843
40,115,LBR,1.814227e+09,1.669959e+09,8.639016
41,199,THA,3.114982e+11,2.867855e+11,8.617158
42,80,GNB,2.059087e+08,1.911277e+08,7.733565
43,64,ERI,6.713626e+08,6.237091e+08,7.640345
44,98,IRQ,8.759556e+10,8.139964e+10,7.611723
45,106,KEN,7.820984e+09,7.270256e+09,7.575082
46,177,SGP,3.764404e+11,3.501084e+11,7.521094
47,0,ABW,2.062528e+08,1.918627e+08,7.500207
48,112,KWT,6.490112e+10,6.044224e+10,7.377100
49,138,MRT,4.414400e+09,4.119756e+09,7.151961
50,158,PCN,6.515562e+06,6.080837e+06,7.149098
51,119,LSO,1.181579e+09,1.103243e+09,7.100553
52,109,KIR,1.053050e+08,9.835694e+07,7.064113
53,67,ETH,4.735318e+09,4.425039e+09,7.011886
54,52,CXR,1.303269e+07,1.219956e+07,6.829112
55,174,SAU,2.784581e+11,2.609898e+11,6.693118
56,197,TCD,2.986532e+09,2.808450e+09,6.340936
57,30,BRA,3.075539e+11,2.892369e+11,6.332857
58,43,COD,2.916041e+10,2.748904e+10,6.080138
59,222,YEM,2.128043e+09,2.008854e+09,5.933170

In [32]:
merged_import.sort_values(by='percentage_difference', ascending =False).head(60)

,importerISO,reconciled_value_trade,reconciled_value_baci,percentage_difference
50,CUB,5.521960e+09,3.413256e+09,61.779841
139,MSR,2.150028e+07,1.579947e+07,36.082275
58,DMA,6.832962e+08,5.971643e+08,14.423494
123,MAC,1.112260e+10,9.895650e+09,12.398914
40,CHN,2.180204e+12,1.978499e+12,10.194831
57,DJI,8.599497e+09,8.205073e+09,4.807084
88,HKG,7.221009e+11,6.890268e+11,4.800107
212,URY,1.250247e+10,1.195685e+10,4.563224
11,ATG,1.202886e+09,1.155667e+09,4.085866
38,CHE,3.407677e+11,3.298630e+11,3.305814
104,JPN,7.230309e+11,7.006666e+11,3.191860
63,EGY,1.004340e+11,9.743634e+10,3.076489
157,PAN,3.909633e+10,3.793048e+10,3.073663
196,TCA,3.026980e+08,2.940479e+08,2.941708
74,GBR,7.031663e+11,6.833071e+11,2.906330
131,MLI,5.612350e+09,5.454785e+09,2.888554
156,PAK,8.100794e+10,7.893219e+10,2.629787
142,MYS,2.508505e+11,2.445930e+11,2.558353
111,KOR,5.919284e+11,5.774225e+11,2.512186
213,USA,2.806596e+12,2.738527e+12,2.485633
75,GEO,1.080796e+10,1.055530e+10,2.393734
218,VNM,3.366740e+11,3.305476e+11,1.853408
22,BHR,1.612053e+10,1.585106e+10,1.700011
106,KEN,2.344573e+10,2.307254e+10,1.617474
216,VEN,7.189357e+09,7.084480e+09,1.480379
175,SDN,8.754470e+09,8.632151e+09,1.417009
76,GHA,2.109802e+10,2.081792e+10,1.345498
116,LBY,1.729865e+10,1.710298e+10,1.144079
51,CUW,1.083426e+09,1.071903e+09,1.074965
195,SYR,4.609244e+09,4.565448e+09,0.959306
16,BEL,4.524988e+11,4.482157e+11,0.955584
180,SLE,1.609011e+09,1.594586e+09,0.904626
71,FRA,7.055200e+11,6.994166e+11,0.872649
82,GRC,7.818285e+10,7.753544e+10,0.834987
198,TGO,1.319272e+10,1.309353e+10,0.757516
173,S19,3.631509e+11,3.604319e+11,0.754388
64,ERI,3.303622e+08,3.280456e+08,0.706168
77,GIB,8.217889e+09,8.162751e+09,0.675481
23,BHS,7.035064e+09,6.989987e+09,0.644867
93,IDN,1.949814e+11,1.937355e+11,0.643048
183,SOM,5.122604e+09,5.091588e+09,0.609164
222,YEM,1.264465e+10,1.257419e+10,0.560389
201,TKL,9.106356e+06,9.073402e+06,0.363193
94,IND,5.803980e+11,5.783838e+11,0.348233
61,DZA,3.476922e+10,3.465192e+10,0.338489
78,GIN,5.327590e+09,5.312006e+09,0.293366
191,SWE,1.744509e+11,1.739507e+11,0.287531
17,BEN,4.979121e+09,4.965504e+09,0.274243
5,AND,1.569217e+09,1.566231e+09,0.190653
114,LBN,1.478470e+10,1.475990e+10,0.168020
136,MNP,6.400563e+07,6.390795e+07,0.152840
91,HTI,4.176757e+09,4.170404e+09,0.152320
219,VUT,3.706752e+08,3.701956e+08,0.129560
39,CHL,8.740483e+10,8.730067e+10,0.119313
20,BGD,7.643066e+10,7.634821e+10,0.107982
197,TCD,1.235764e+09,1.234466e+09,0.105132
80,GNB,4.218515e+08,4.214230e+08,0.101674
224,ZMB,6.822221e+09,6.815486e+09,0.098816
33,BTN,1.122455e+09,1.121433e+09,0.091166
144,NCL,2.202906e+09,2.200922e+09,0.090116

In [ ]:
#merged_export.to_csv('merged_export.csv', index=False)
#merged_import.to_csv('merged_import.csv', index=False)

In [33]:
trade_df_copy = trade_df.copy()
Baci_2021_copy = Baci_2021.copy()
#atlas_2022_copy = atlas_2022.copy()

In [34]:
# Applying thresholds
threshold_country = 1500000000
threshold_HS = 500000000
# Filter out countries
df_country =  trade_df_copy.groupby('exporterISO')['reconciled_value'].sum()
trade_df_copy = trade_df_copy[~trade_df_copy['exporterISO'].isin(df_country[df_country < threshold_country].index)]

# Filter out products (HS4)
df_HS = trade_df_copy.groupby('HS4_code')['reconciled_value'].sum()
trade_df_copy = trade_df_copy[~trade_df_copy['HS4_code'].isin(df_HS[df_HS < threshold_HS].index)]

In [35]:
# Applying thresholds
threshold_country = 1500000000
threshold_HS = 500000000

# Filter out countries
df_country =  Baci_2021_copy.groupby('exporterISO')['reconciled_value'].sum()
Baci_2021_copy = Baci_2021_copy[~Baci_2021_copy['exporterISO'].isin(df_country[df_country < threshold_country].index)]

# Filter out products (HS4)
df_HS = Baci_2021_copy.groupby('HS4_code')['reconciled_value'].sum()
Baci_2021_copy = Baci_2021_copy[~Baci_2021_copy['HS4_code'].isin(df_HS[df_HS < threshold_HS].index)]

In [36]:
print(trade_df_copy['exporterISO'].nunique())
print(trade_df_copy['HS4_code'].nunique())

153
1031

In [37]:
print(Baci_2021_copy['exporterISO'].nunique())
print(Baci_2021_copy['HS4_code'].nunique())

150
1042

In [38]:
comp = econci.Complexity(trade_df_copy, c='exporterISO', p='HS4_code', values='reconciled_value')
comp.calculate_indexes()

In [39]:
comp_baci = econci.Complexity(Baci_2021_copy, c='exporterISO', p='HS4_code', values='reconciled_value')
comp_baci.calculate_indexes()

In [40]:
eci = comp.eci
pci = comp.pci

In [41]:
eci_1 = comp_baci.eci
pci_1 = comp_baci.pci

In [42]:
# create dataframes
eci = eci.rename(columns={0: "ECI"}).reset_index()
pci = pci.rename(columns={0: "PCI"}).reset_index()

In [43]:
eci_1 = eci_1.rename(columns={0: "ECI"}).reset_index()
pci_1 = pci_1.rename(columns={0: "PCI"}).reset_index()

In [44]:
# display data
print(" Highest ECIs")
eci.sort_values(by='eci',ascending=False).head()

 Highest ECIs

     index exporterISO       eci
70      70         JPN  2.241578
121    121         S19  2.163442
23      23         CHE  2.011053
75      75         KOR  1.920897
36      36         DEU  1.786868

In [45]:
print("5 Highest ECIs")
eci_1.sort_values(by='eci',ascending=False).head()

5 Highest ECIs

     index exporterISO       eci
68      68         JPN  2.235182
118    118         S19  2.185782
73      73         KOR  1.967377
22      22         CHE  1.862032
34      34         DEU  1.790180

In [46]:
# display data
print("5 Highest PCIs")
pci.sort_values(by='pci',ascending=False).head()

5 Highest PCIs

     index HS4_code       pci
354    354     3705  2.596775
257    257     2843  2.022155
368    368     3818  2.005458
960    960     9010  1.998831
840    840     8457  1.944631

In [47]:
print("5 Highest PCIs")
pci_1.sort_values(by='pci',ascending=False).head()

5 Highest PCIs

     index HS4_code       pci
356    356     3705  2.297461
969    969     9010  2.289058
357    357     3707  2.136160
259    259     2843  2.074266
371    371     3818  2.060281

differences

In [49]:
# Align indexes
trade_df = trade_df.sort_index()
Baci_2021 = Baci_2021.sort_index()

In [50]:
common_cols = Baci_2021.columns.intersection(trade_df.columns)
Baci_2021 = Baci_2021[common_cols]
trade_df = trade_df[common_cols]

In [51]:
# Unique exporters and importers in each DataFrame
exporters_trade = set(trade_df['exporterISO'].unique())
exporters_Baci = set(Baci_2021['exporterISO'].unique())


importers_trade = set(trade_df['importerISO'].unique())
importers_Baci = set(Baci_2021['importerISO'].unique())

cmd_trade = set(trade_df['HS4_code'].unique())
cmd_Baci = set(Baci_2021['HS4_code'].unique())

# Differences in exporters
exporters_only_in_Baci = exporters_Baci - exporters_trade
exporters_only_in_trade  = exporters_trade - exporters_Baci

# Differences in importers
importers_only_in_Baci = importers_Baci - importers_trade
importers_only_in_trade = importers_trade - importers_Baci

#Difference in cmdcode
cmd_only_in_Baci = cmd_Baci - cmd_trade
cmd_only_in_trade = cmd_trade - cmd_Baci

In [52]:
# Print results
print("Exporters only in BACI:", exporters_only_in_Baci)
print("Exporters only in trade_df:", exporters_only_in_trade)

Exporters only in BACI: set()
Exporters only in trade_df: set()

In [53]:
print("Importers only in BACI:", importers_only_in_Baci)
print("Importers only in trade_df:", importers_only_in_trade)

Importers only in BACI: set()
Importers only in trade_df: set()

In [54]:
print("cmdCode only in BACI:", cmd_only_in_Baci)
print("cmdCode only in trade_df:", cmd_only_in_trade)

cmdCode only in BACI: set()
cmdCode only in trade_df: set()

In [55]:
# Merge the two DataFrames
validation_df = trade_df.merge(
    Baci_2021,
    on=['HS4_code','exporterISO', 'importerISO', 'period'],
    how='outer',
    suffixes=('_trade', '_baci'),
    indicator=True
)

In [56]:
validation_df.head(20)

,HS4_code,H0_trade,period,reconciled_value_trade,exporterISO,importerISO,H0_baci,reconciled_value_baci,_merge
0,0101,010111,2021,4139.0,ABW,COL,010111,4811.0,both
1,0101,010119,2021,2793.0,ABW,CUW,010119,2793.0,both
2,0101,010120,2021,1955.0,ABW,NLD,010120,1955.0,both
3,0101,010111,2021,4491.0,AFG,ESP,010111,4491.0,both
4,0101,010111,2021,18.0,AFG,IRL,010111,18.0,both
5,0101,010119,2021,1100.0,AFG,TJK,010119,1100.0,both
6,0101,010119,2021,9700.0,AFG,UZB,010119,9700.0,both
7,0101,010111,2021,174.0,AGO,BRA,010111,174.0,both
8,0101,010111,2021,1584.0,AGO,COD,010111,1575.0,both
9,0101,010111,2021,1584.0,AGO,COD,010119,5629.0,both
10,0101,010119,2021,1655.0,AGO,COD,010111,1575.0,both
11,0101,010119,2021,1655.0,AGO,COD,010119,5629.0,both
12,0101,010119,2021,3974.0,AGO,COD,010111,1575.0,both
13,0101,010119,2021,3974.0,AGO,COD,010119,5629.0,both
14,0101,010111,2021,79.0,AGO,IND,010111,79.0,both
15,0101,010111,2021,314.0,AGO,PRT,010111,314.0,both
16,0101,010111,2021,119.0,AGO,ZAF,010111,119.0,both
17,0101,010119,2021,471.0,AND,ESP,010119,72049.0,both
18,0101,010119,2021,71638.0,AND,ESP,010119,72049.0,both
19,0101,010111,2021,2353.0,AND,FRA,010111,2353.0,both

In [57]:
# Rows only in trade_df
only_in_trade = validation_df[validation_df['_merge'] == 'left_only']
# Rows only in Baci_2022
only_in_baci = validation_df[validation_df['_merge'] == 'right_only']
# Rows that are both
both = validation_df[validation_df['_merge'] == 'both']

In [58]:
print(only_in_trade.shape)
only_in_trade.sort_values(by='reconciled_value_trade', ascending=True).head(40)

(38812, 9)

,HS4_code,H0_trade,period,reconciled_value_trade,exporterISO,importerISO,H0_baci,reconciled_value_baci,_merge
7066667,3214,321410,2021,1.0,EGY,RUS,NaN,NaN,left_only
26096351,7319,731990,2021,1.0,CPV,ESP,NaN,NaN,left_only
24064845,7210,721090,2021,1.0,KHM,CHN,NaN,NaN,left_only
1593165,0901,090111,2021,1.0,GHA,CUB,NaN,NaN,left_only
3871755,2507,250700,2021,1.0,MKD,BEL,NaN,NaN,left_only
27777667,8211,821194,2021,1.0,GHA,USA,NaN,NaN,left_only
22934494,6807,680710,2021,1.0,TTO,ARE,NaN,NaN,left_only
29607415,8418,841829,2021,1.0,BHS,HTI,NaN,NaN,left_only
41449720,9026,902680,2021,1.0,BHS,GBR,NaN,NaN,left_only
38780588,8703,870390,2021,1.0,BHS,HTI,NaN,NaN,left_only
11959001,4704,470421,2021,1.0,THA,JPN,NaN,NaN,left_only
26852509,7616,761690,2021,1.0,KNA,MSR,NaN,NaN,left_only
11886483,4421,442110,2021,1.0,CAN,LBR,NaN,NaN,left_only
44286843,9606,960610,2021,1.0,MNG,RUS,NaN,NaN,left_only
11861790,4419,441900,2021,1.0,GHA,TZA,NaN,NaN,left_only
44294868,9606,960629,2021,1.0,TGO,GHA,NaN,NaN,left_only
25905501,7318,731829,2021,1.0,NER,GHA,NaN,NaN,left_only
23382689,7013,701310,2021,1.0,GHA,QAT,NaN,NaN,left_only
23382685,7013,701310,2021,1.0,GHA,NOR,NaN,NaN,left_only
8060344,3809,380991,2021,1.0,GHA,UGA,NaN,NaN,left_only
26342951,7324,732429,2021,1.0,HKG,BHS,NaN,NaN,left_only
24744581,7304,730490,2021,1.0,MYS,BEL,NaN,NaN,left_only
26973328,8201,820140,2021,1.0,GHA,COG,NaN,NaN,left_only
15537372,5802,580211,2021,1.0,GHA,LBR,NaN,NaN,left_only
15537382,5802,580219,2021,1.0,GHA,SLE,NaN,NaN,left_only
27160836,8204,820412,2021,1.0,CPV,ESP,NaN,NaN,left_only
12640012,4820,482010,2021,1.0,CHE,LBR,NaN,NaN,left_only
12664198,4820,482020,2021,1.0,GHA,SLE,NaN,NaN,left_only
26645779,7419,741999,2021,1.0,GBR,CPV,NaN,NaN,left_only
23148715,6914,691490,2021,1.0,ARG,BOL,NaN,NaN,left_only
22176574,6306,630612,2021,1.0,PHL,BHS,NaN,NaN,left_only
10048498,3926,392690,2021,1.0,LSO,NAM,NaN,NaN,left_only
34421171,8484,848490,2021,1.0,BHS,ITA,NaN,NaN,left_only
21712290,6302,630229,2021,1.0,GHA,GBR,NaN,NaN,left_only
21712296,6302,630260,2021,1.0,GHA,LBR,NaN,NaN,left_only
38202386,8542,854219,2021,1.0,EGY,MAR,NaN,NaN,left_only
38145731,8541,854110,2021,1.0,PER,GTM,NaN,NaN,left_only
3849921,2501,250100,2021,1.0,BEL,UZB,NaN,NaN,left_only
11751500,4412,441299,2021,1.0,BHS,HTI,NaN,NaN,left_only
12182114,4808,480810,2021,1.0,PRT,MKD,NaN,NaN,left_only

In [59]:
print(only_in_baci.shape)
only_in_baci.sort_values(by='reconciled_value_baci', ascending=True).head(40)

(630938, 9)

,HS4_code,H0_trade,period,reconciled_value_trade,exporterISO,importerISO,H0_baci,reconciled_value_baci,_merge
23093694,6909,NaN,2021,NaN,RUS,AUT,690911,1.0,right_only
12891606,4903,NaN,2021,NaN,TUR,GTM,490300,1.0,right_only
26221035,7321,NaN,2021,NaN,VNM,MDV,732113,1.0,right_only
31603729,8435,NaN,2021,NaN,CYP,NLD,843510,1.0,right_only
8590817,3908,NaN,2021,NaN,AUS,CAN,390810,1.0,right_only
27827729,8212,NaN,2021,NaN,RWA,ZAF,821210,1.0,right_only
42288379,9103,NaN,2021,NaN,DEU,CRI,910390,1.0,right_only
36732373,8524,NaN,2021,NaN,ZAF,KOR,852410,1.0,right_only
7922812,3703,NaN,2021,NaN,PAK,CAN,370390,1.0,right_only
42351630,9108,NaN,2021,NaN,CHE,BMU,910899,1.0,right_only
13064635,5204,NaN,2021,NaN,RUS,TLS,520420,1.0,right_only
22255476,6310,NaN,2021,NaN,ARE,NIC,631010,1.0,right_only
2935645,2005,NaN,2021,NaN,CHE,ZAF,200559,1.0,right_only
2212562,1515,NaN,2021,NaN,ITA,SLV,151590,1.0,right_only
38628664,8546,NaN,2021,NaN,JPN,KAZ,854690,1.0,right_only
32214566,8452,NaN,2021,NaN,RUS,FRA,845230,1.0,right_only
26100878,7319,NaN,2021,NaN,NLD,GUY,731990,1.0,right_only
44265744,9606,NaN,2021,NaN,CAN,SYC,960610,1.0,right_only
24155522,7214,NaN,2021,NaN,CHE,CIV,721440,1.0,right_only
22948737,6809,NaN,2021,NaN,TUR,SLV,680990,1.0,right_only
11574126,4205,NaN,2021,NaN,BGD,ZAF,420500,1.0,right_only
27156073,8204,NaN,2021,NaN,BLR,NZL,820411,1.0,right_only
22255589,6310,NaN,2021,NaN,AUS,LKA,631010,1.0,right_only
1305780,0802,NaN,2021,NaN,ARG,ZAF,080290,1.0,right_only
6217107,2936,NaN,2021,NaN,IND,MRT,293628,1.0,right_only
32412452,8461,NaN,2021,NaN,CAN,SYC,846150,1.0,right_only
6227318,2936,NaN,2021,NaN,LKA,CAN,293627,1.0,right_only
22256147,6310,NaN,2021,NaN,BRA,AUT,631090,1.0,right_only
12615870,4819,NaN,2021,NaN,TUR,BWA,481940,1.0,right_only
2934827,2005,NaN,2021,NaN,CAN,DNK,200551,1.0,right_only
9624094,3922,NaN,2021,NaN,CHE,TZA,392210,1.0,right_only
27742189,8209,NaN,2021,NaN,MEX,HUN,820900,1.0,right_only
22689246,6601,NaN,2021,NaN,QAT,ZAF,660199,1.0,right_only
4189702,2813,NaN,2021,NaN,CHN,ZWE,281310,1.0,right_only
17274136,6104,NaN,2021,NaN,S19,ETH,610443,1.0,right_only
18433236,6117,NaN,2021,NaN,URY,ARE,611710,1.0,right_only
2537597,1701,NaN,2021,NaN,SAU,ZAF,170199,1.0,right_only
2539048,1701,NaN,2021,NaN,THA,ETH,170191,1.0,right_only
18434791,6117,NaN,2021,NaN,ZWE,ZAF,611710,1.0,right_only
18434792,6117,NaN,2021,NaN,ZWE,ZAF,611790,1.0,right_only

In [60]:
print(both.shape)
both.head(20)

(43900565, 9)

,HS4_code,H0_trade,period,reconciled_value_trade,exporterISO,importerISO,H0_baci,reconciled_value_baci,_merge
0,0101,010111,2021,4139.0,ABW,COL,010111,4811.0,both
1,0101,010119,2021,2793.0,ABW,CUW,010119,2793.0,both
2,0101,010120,2021,1955.0,ABW,NLD,010120,1955.0,both
3,0101,010111,2021,4491.0,AFG,ESP,010111,4491.0,both
4,0101,010111,2021,18.0,AFG,IRL,010111,18.0,both
5,0101,010119,2021,1100.0,AFG,TJK,010119,1100.0,both
6,0101,010119,2021,9700.0,AFG,UZB,010119,9700.0,both
7,0101,010111,2021,174.0,AGO,BRA,010111,174.0,both
8,0101,010111,2021,1584.0,AGO,COD,010111,1575.0,both
9,0101,010111,2021,1584.0,AGO,COD,010119,5629.0,both
10,0101,010119,2021,1655.0,AGO,COD,010111,1575.0,both
11,0101,010119,2021,1655.0,AGO,COD,010119,5629.0,both
12,0101,010119,2021,3974.0,AGO,COD,010111,1575.0,both
13,0101,010119,2021,3974.0,AGO,COD,010119,5629.0,both
14,0101,010111,2021,79.0,AGO,IND,010111,79.0,both
15,0101,010111,2021,314.0,AGO,PRT,010111,314.0,both
16,0101,010111,2021,119.0,AGO,ZAF,010111,119.0,both
17,0101,010119,2021,471.0,AND,ESP,010119,72049.0,both
18,0101,010119,2021,71638.0,AND,ESP,010119,72049.0,both
19,0101,010111,2021,2353.0,AND,FRA,010111,2353.0,both

In [61]:
# Filter rows that are present in both DataFrames
matching_rows = validation_df[validation_df['_merge'] == 'both']

# Identify rows with mismatched reconciled_value
diffs = matching_rows[
    matching_rows['reconciled_value_trade'] != matching_rows['reconciled_value_baci']
]

# View differences
print(diffs.shape[0])
diffs.head()

39896608

,HS4_code,H0_trade,period,reconciled_value_trade,exporterISO,importerISO,H0_baci,reconciled_value_baci,_merge
0,0101,010111,2021,4139.0,ABW,COL,010111,4811.0,both
8,0101,010111,2021,1584.0,AGO,COD,010111,1575.0,both
9,0101,010111,2021,1584.0,AGO,COD,010119,5629.0,both
10,0101,010119,2021,1655.0,AGO,COD,010111,1575.0,both
11,0101,010119,2021,1655.0,AGO,COD,010119,5629.0,both

In [ ]:
both.shape[0] - diffs.shape[0]

3914033

In [ ]:
Baci_2022.shape[0] - trade_df.shape[0]

542636