In [1]:
#!pip install --upgrade comtradeapicall

In [2]:
import pandas as pd
import requests
import comtradeapicall
import numpy as np
from itertools import count
import json
import math
import os
import requests
from IPython.display import clear_output

In [3]:
## configuration
relative_data_path = r'C:\Users\Administrator\Personal-Projects\Trade_data_Analysis\Data'
subscription_key = os.getenv("comtrade_subscription_key")
pd.set_option('display.max_columns', None)

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
# READ H0 HS DATA
url = "https://comtradeapi.un.org/files/v1/app/reference/H6.json"
response = requests.get(url)
data = response.json()
HS_2022 = pd.DataFrame(data)
HS_2022.head()

,more,minimumInputLength,classCode,className,results
0,False,2,H6,HS2022,"{'id': 'TOTAL', 'text': 'Total - All H6 commod..."
1,False,2,H6,HS2022,"{'id': '01', 'text': '01 - Animals; live', 'pa..."
2,False,2,H6,HS2022,"{'id': '0101', 'text': '0101 - Horses, asses, ..."
3,False,2,H6,HS2022,"{'id': '010121', 'text': '010121 - Horses; liv..."
4,False,2,H6,HS2022,"{'id': '010129', 'text': '010129 - Horses; liv..."

In [6]:
f = open('C:\\Users\\Administrator\\Personal-Projects\\Trade_data_Analysis\\Trade notebooks\\HS.json',encoding='utf-8')
hs_data = json.load(f)

In [7]:
path2 = 'C:\\Users\\Administrator\\Personal-Projects\\Trade_data_Analysis\\Trade notebooks\\country_codes_V202401b.csv'
country_codes = pd.read_csv(path2)
codes = country_codes['country_code'].to_list()
print(codes)
country_codes.head()

[4, 8, 12, 16, 20, 24, 28, 31, 32, 36, 40, 44, 48, 50, 51, 52, 56, 58, 60, 64, 68, 70, 72, 76, 84, 86, 90, 92, 96, 100, 104, 108, 112, 116, 120, 124, 132, 136, 140, 144, 148, 152, 156, 162, 166, 170, 174, 175, 178, 180, 184, 188, 191, 192, 196, 200, 203, 204, 208, 212, 214, 218, 222, 226, 231, 232, 233, 238, 242, 246, 251, 258, 260, 262, 266, 268, 270, 275, 276, 278, 280, 288, 292, 296, 300, 304, 308, 316, 320, 324, 328, 332, 340, 344, 348, 352, 360, 364, 368, 372, 376, 380, 384, 388, 392, 398, 400, 404, 408, 410, 414, 417, 418, 422, 426, 428, 430, 434, 440, 442, 446, 450, 454, 458, 462, 466, 470, 478, 480, 484, 490, 496, 498, 499, 500, 504, 508, 512, 516, 520, 524, 528, 530, 531, 533, 534, 535, 540, 548, 554, 558, 562, 566, 570, 574, 579, 580, 583, 584, 585, 586, 591, 598, 600, 604, 608, 612, 616, 620, 624, 626, 634, 642, 643, 646, 652, 654, 659, 660, 662, 666, 670, 674, 678, 682, 686, 688, 690, 694, 697, 699, 702, 703, 704, 705, 706, 710, 711, 716, 724, 728, 729, 736, 740, 748, 752, 757, 760, 762, 764, 768, 772, 776, 780, 784, 788, 792, 795, 796, 798, 800, 804, 807, 810, 818, 826, 834, 842, 849, 854, 858, 860, 862, 876, 882, 887, 891, 894]

   country_code    country_name country_iso2 country_iso3
0             4     Afghanistan           AF          AFG
1             8         Albania           AL          ALB
2            12         Algeria           DZ          DZA
3            16  American Samoa           AS          ASM
4            20         Andorra           AD          AND

### Fuctions to Extract the Data

In [8]:
def getFinalDataBulkAvailability(subscription_key, typeCode, freqCode, clCode, period, reporterCode, publishedDateFrom=None, publishedDateTo=None):
    return getDataAvailability(subscription_key, 'FINAL', 'BULK', typeCode, freqCode, clCode, period, reporterCode, publishedDateFrom, publishedDateTo)

In [9]:
def split_numbers(input_string, chunk_size):
    # Split the string by commas to get a list of numbers
    numbers = input_string.split(',')

    # Group the numbers into chunks of specified size
    chunks = [numbers[i:i + chunk_size] for i in range(0, len(numbers), chunk_size)]

    return chunks

In [10]:
def get_data_from_uncomtrade(reporter,partner,flowCode,frequency,data_date,hs_code,hs_2_digit=None,hs_4_digit=None,hs_6_digit=None,include_none=False):

    """
    Fetch trade data from UN Comtrade based on specified criteria.

    Parameters:
    - reporter (str or list): Reporting country or countries.
    - partner (str or list): Partner country or countries.
    - frequency (str): Data frequency (e.g., 'annual', 'monthly').
    - data_date (str): Data period(s) in a comma-separated string.
    - hs_code (list or str): HS codes to retrieve data for, or "00" for all 2-digit codes.
    - hs_2_digit, hs_4_digit, hs_6_digit (bool): Flags to include specific HS code levels.
    - include_none (bool): If False, excludes rows with None values in the output.

    Returns:
    - final_dataframe (DataFrame): Raw trade data from the API.
    - test_dataframe (DataFrame): Processed trade data with comparisons.
    """

    if isinstance(data_date, str):
        years_list = data_date.split(',')
        # Check the length of the list and truncate if necessary
        if len(years_list) > 12:
            print("Maximum 12 date periods can be used in date string per call")
            return None,None

    if isinstance(reporter, list):
        string_list = [str(item) for item in reporter]
        reporter = ','.join(map(str, reporter))
    elif isinstance(reporter, str):
        pass
    else:
        print("The reporter codes should be a list or comma seperated string.")
        return None

    if isinstance(partner, list):
        string_list = [str(item) for item in partner]
        partner = ','.join(map(str, partner))
    elif isinstance(partner, str):
        pass
    else:
        print("The partner codes should be a list or comma seperated string.")
        return None

    if isinstance(hs_code, list) or hs_code=="00":
        pass
    else:
        print(f"""HS code must be passed as a list of strings or should be "00" """)
        return None
    if not hs_code:
        result = True
    else:
        # Get the length of the first element
        first_length = len(hs_code[0])

        # Check if all elements have the same length
        result = all(len(item) == first_length for item in hs_code)

    if result==False:
        print("The hs code string should include only 2,4 or 6 digitis as list do not send mixed digits hs code.")
        return None
    ############################################################
    if hs_code=="00":
        hs_list_2_digit=[]
        for item in hs_data["results"]:
            if item["aggrLevel"]==2:
                hs_list_2_digit.append(item['id'])
        codes_string = ','.join(map(str, hs_list_2_digit))
        final_dataframe = comtradeapicall.getFinalData(subscription_key, typeCode='C', freqCode=frequency, clCode='HS', period=data_date,
                                        reporterCode=reporter, cmdCode=codes_string, flowCode=flowCode, partnerCode=partner,
                                        partner2Code=None, customsCode=None, motCode=None, maxRecords=250000,
                                        format_output='JSON', aggregateBy=None, breakdownMode='classic',
                                        countOnly=None, includeDesc=True)
    ############################################################
    else:
        string_list = [str(item) for item in hs_code]
        if len(string_list[0])==2:

            codes_string_2_digit = ','.join(map(str, hs_code))
            hs_list_4_digit=[]
            for item in hs_data["results"]:
                if item["aggrLevel"]==4 and item["parent"] in hs_code:
                    hs_list_4_digit.append(item['id'])
            codes_string_4_digit = ','.join(map(str, hs_list_4_digit))
            hs_list_6_digit=[]
            for item in hs_data["results"]:
                if item["aggrLevel"]==6 and item["parent"] in hs_list_4_digit:
                    hs_list_6_digit.append(item['id'])
            codes_string_6_digit = ','.join(map(str, hs_list_6_digit))


        elif len(string_list[0])==4:
            for item in hs_code:
                unique_first_two_digits = set()
                # Extract the first two digits
                first_two_digits = item[:2]
                # Add the first two digits to the set
                unique_first_two_digits.add(first_two_digits)
            # Convert the set to a list if needed
            unique_first_two_digits_list = list(unique_first_two_digits)
            codes_string_2_digit = ','.join(map(str, unique_first_two_digits_list))
            codes_string_4_digit=','.join(map(str, hs_code))
            hs_list_6_digit=[]
            for item in hs_data["results"]:
                if item["aggrLevel"]==6 and item["parent"] in hs_code:
                    hs_list_6_digit.append(item['id'])
            codes_string_6_digit = ','.join(map(str, hs_list_6_digit))

        elif len(string_list[0])==6:
            for item in hs_code:
                unique_first_four_digits = set()
                # Extract the first two digits
                first_four_digits = item[:4]
                # Add the first two digits to the set
                unique_first_four_digits.add(first_four_digits)
            # Convert the set to a list if needed
            unique_first_four_digits_list = list(unique_first_four_digits)
            codes_string_4_digit = ','.join(map(str, unique_first_four_digits_list))
            for item in unique_first_four_digits_list:
                unique_first_two_digits = set()
                # Extract the first two digits
                first_two_digits = item[:2]
                # Add the first two digits to the set
                unique_first_two_digits.add(first_two_digits)
            # Convert the set to a list if needed
            unique_first_two_digits_list = list(unique_first_two_digits)
            codes_string_2_digit = ','.join(map(str, unique_first_two_digits_list))
            codes_string_6_digit=','.join(map(str, hs_code))

        else:
            print("The hs code string should include only 2,4 or 6 digitis as list do not send mixed digits hs code.")
            return None
        if(hs_2_digit==False and hs_4_digit==False and hs_6_digit==False):
            print("At least one of the digit selections must be True")
            return None
        codes_string=""
        if(hs_2_digit==True):
            codes_string+=codes_string_2_digit+","
        if(hs_4_digit==True):
            codes_string+=codes_string_4_digit+","
        if(hs_6_digit==True):
            codes_string+=codes_string_6_digit
        codes_string = codes_string.rstrip(',')
        print(f"""Final codes_string= {codes_string} """)
        chunk_size = 100
        chunks = split_numbers(codes_string, chunk_size)
        final_dataframe=pd.DataFrame()
        for chunk in range(0,len(chunks),1):
            string_numbers = list(map(str, chunks[chunk]))
            codes_string = ','.join(map(str, string_numbers))
            mydf = comtradeapicall.getFinalData(subscription_key, typeCode='C', freqCode=frequency, clCode='HS', period=data_date,
                                        reporterCode=reporter, cmdCode=codes_string, flowCode=flowCode, partnerCode=partner,
                                        partner2Code=None, customsCode=None, motCode=None, maxRecords=250000,
                                        format_output='JSON', aggregateBy=None, breakdownMode='classic',
                                        countOnly=None, includeDesc=True)
            final_dataframe=pd.concat([final_dataframe,mydf])
        final_dataframe=final_dataframe.reset_index(drop=True)
        return final_dataframe
    ##################################################################### Added for non equal price  check
    columns = ['cifvalue', 'fobvalue', 'primaryValue']
    # Initialize the result to True

    # Initialize an empty DataFrame to store rows with differences
    rows_with_differences = []

    # Loop through each row in the final_dataframe
    for _, row in final_dataframe.iterrows():
        # Extract the values for the specified columns
        values = [row[col] for col in columns]

        # Filter out NaN values and zeros
        non_nan_values = [value for value in values if pd.notna(value) and value != 0.0]

        # Check if all non-NaN values are the same
        if len(set(non_nan_values)) > 1:
            # If there are differences, add the row to the list
            rows_with_differences.append(row)

    # Concatenate all rows with differences into a DataFrame
    failures_dataframe = pd.DataFrame(rows_with_differences)

    # Check if any differences were found and output the result
    if not failures_dataframe.empty:
        print("There are differences in the price columns")

    ####################################################################
    test_dataframe=pd.DataFrame()
    periods_list = final_dataframe['period'].unique().tolist()
    for periods in periods_list:
        filtered_df=final_dataframe[final_dataframe["period"]==periods]

        reporter_numbers = filtered_df['reporterCode'].unique().tolist()
        for reporter_loop in reporter_numbers:
            unique_numbers = filtered_df[filtered_df["reporterCode"]==reporter_loop]['cmdCode'].unique().tolist()
            for hs_codes in unique_numbers:
                mydf=filtered_df[(filtered_df["cmdCode"]==hs_codes)&(filtered_df["reporterCode"]==reporter_loop)]
                unique_partners = mydf['partnerCode'].unique().tolist()
                if len(unique_partners)>1:
                    if unique_partners[0] == 0:
                        unique_partners = unique_partners[1:]

                for partners in unique_partners:
                    mydf=filtered_df[(filtered_df["cmdCode"]==hs_codes)&(filtered_df["reporterCode"]==reporter_loop)&(filtered_df["partnerCode"]==partners)]
                    # Check if mydf is empty
                    if mydf.empty:
                        import_quantity = None
                        export_quantity = None
                        import_amount= None
                        export_amount= None
                        unit_type = None
                        difference = None
                        balance_status = None
                        Hs_description=None
                        country_tag=None
                        reporter=None
                        partner=None
                        difference_amount = None
                        balance_status_dollars = None
                        total_parent=None
                        period_data=None
                    else:
                        flow_list=mydf["flowCode"].unique().tolist()
                        if "X" not in flow_list or "M" not in flow_list:
                            continue

                        try:
                            if mydf[mydf['flowCode'] == 'M']['qty'].values[0]!=0 and mydf[mydf['flowCode'] == 'X']['qty'].values[0]!=0 :
                                import_quantity = mydf[mydf['flowCode'] == 'M']['qty'].values[0]
                                export_quantity = mydf[mydf['flowCode'] == 'X']['qty'].values[0]
                                unit_type = mydf[mydf['flowCode'] == 'X']['qtyUnitAbbr'].values[0] if not mydf[mydf['flowCode'] == 'X']['qtyUnitAbbr'].empty else None
                            else:
                                import_quantity = mydf[mydf['flowCode'] == 'M']['altQty'].values[0] if not mydf[mydf['flowCode'] == 'M']['altQty'].empty else None
                                export_quantity = mydf[mydf['flowCode'] == 'X']['altQty'].values[0] if not mydf[mydf['flowCode'] == 'X']['altQty'].empty else None
                                unit_type = mydf[mydf['flowCode'] == 'X']['altQtyUnitAbbr'].values[0] if not mydf[mydf['flowCode'] == 'X']['altQtyUnitAbbr'].empty else None
                            ################################################ Under this part new value selector selects any not NaN
                            columns = ['cifvalue', 'fobvalue', 'primaryValue']
                            # Initialize variables
                            import_amount = None
                            export_amount = None
                            # Check for the first non-NaN, non-0.0 value for 'M'
                            for col in columns:
                                values = mydf[mydf['flowCode'] == 'M'][col].values
                                if len(values) > 0 and pd.notna(values[0]) and values[0] != 0.0:
                                    import_amount = values[0]
                                    break
                            # Check for the first non-NaN, non-0.0 value for 'X'
                            for col in columns:
                                values = mydf[mydf['flowCode'] == 'X'][col].values
                                if len(values) > 0 and pd.notna(values[0]) and values[0] != 0.0:
                                    export_amount = values[0]
                                    break
                            # If either import_amount or export_amount is None, set both to None
                            if import_amount is None or export_amount is None:
                                import_amount = None
                                export_amount = None

                        except IndexError as e:
                            print("IndexError occurred:", e)
                            print("DataFrame mydf:")
                            return final_dataframe,mydf


                        Hs_description=mydf[mydf['flowCode'] == 'X']['cmdDesc'].values[0] if not mydf[mydf['flowCode'] == 'X']['cmdDesc'].empty else None
                        country_tag = mydf[mydf['flowCode'] == 'X']['reporterISO'].values[0]
                        reporter = mydf[mydf['flowCode'] == 'X']['reporterCode'].values[0]
                        partner_tag= mydf[mydf['flowCode'] == 'X']['partnerDesc'].values[0]
                        partner=mydf[mydf['flowCode'] == 'X']['partnerCode'].values[0]
                        # Calculate the differences and balance status
                        if export_quantity is not None and import_quantity is not None:
                            difference = export_quantity - import_quantity
                            balance_status = "Positive" if difference > 0 else "Negative"
                        else:
                            difference = None
                            balance_status = None

                        if export_amount is not None and import_amount is not None:
                            difference_amount = export_amount - import_amount
                            balance_status_dollars = "Positive" if difference_amount > 0 else "Negative"
                        else:
                            difference_amount = None
                            balance_status_dollars = None


                    if include_none==False:
                        if difference==None and difference_amount==None:
                            continue

                    total_parent=None
                    if len(hs_codes)>2:
                        total_parent=hs_codes[:2]
                    data = pd.DataFrame([{
                    "Period": periods,
                    "HS Code": hs_codes,
                    "Parent": total_parent,
                    "Reporter Code": reporter,
                    "Reporter": country_tag,
                    "Partner Code": partner,
                    "Partner": partner_tag,
                    "HS_Description": Hs_description,
                    "Unit Type": unit_type,
                    "Import Quantitiy": import_quantity,
                    "Export Quantitiy": export_quantity,
                    "Import/Export Diff Quantity": difference,
                    "Import/Export Balance Quantity": balance_status,
                    "Import Amount Dollars": import_amount,
                    "Export Amount Dollars": export_amount,
                    "Import/Export Diff Dollars": difference_amount,
                    "Import/Export Balance Dollars": balance_status_dollars
                }])
                    test_dataframe = pd.concat([test_dataframe, data], ignore_index=True)
    if len(failures_dataframe)>0:
        return final_dataframe,test_dataframe
    else:
        return final_dataframe,test_dataframe

Get all the HS codes data reportered

In [11]:
uncomtrade_data_hs_2,balanced_dataframe_hs_2=get_data_from_uncomtrade(reporter="270",partner=codes, flowCode ="X",frequency="A",data_date="2022",hs_code="00",hs_2_digit=False,hs_4_digit=False,hs_6_digit=True)

In [12]:
positive_top_5_items=uncomtrade_data_hs_2["cmdCode"].unique().tolist()

This calls all the exports/imports data of all countries to a specific country, the values returned are close to the onesin Atlas Dataset and BACI Datasets. All you need to change is the partners code and year

In [13]:
gambia_exports_2022 =get_data_from_uncomtrade(reporter="270",partner=codes,data_date="2022",flowCode='X', frequency="A", hs_code=positive_top_5_items,hs_2_digit=False,hs_4_digit=False,hs_6_digit=True)

Final codes_string= 030110,030111,030119,030191,030192,030193,030194,030195,030199,030211,030212,030213,030214,030219,030221,030222,030223,030224,030229,030231,030232,030233,030234,030235,030236,030239,030240,030241,030242,030243,030244,030245,030246,030247,030249,030250,030251,030252,030253,030254,030255,030256,030259,030261,030262,030263,030264,030265,030266,030267,030268,030269,030270,030271,030272,030273,030274,030279,030281,030282,030283,030284,030285,030289,030290,030291,030292,030299,030310,030311,030312,030313,030314,030319,030321,030322,030323,030324,030325,030326,030329,030331,030332,030333,030334,030339,030341,030342,030343,030344,030345,030346,030349,030350,030351,030352,030353,030354,030355,030356,030357,030359,030360,030361,030362,030363,030364,030365,030366,030367,030368,030369,030371,030372,030373,030374,030375,030376,030377,030378,030379,030380,030381,030382,030383,030384,030389,030390,030391,030392,030399,030410,030411,030412,030419,030420,030421,030422,030429,030431,030432,030433,030439,030441,030442,030443,030444,030445,030446,030447,030448,030449,030451,030452,030453,030454,030455,030456,030457,030459,030461,030462,030463,030469,030471,030472,030473,030474,030475,030479,030481,030482,030483,030484,030485,030486,030487,030488,030489,030490,030491,030492,030493,030494,030495,030496,030497,030499,030510,030520,030530,030531,030532,030539,030541,030542,030543,030544,030549,030551,030552,030553,030554,030559,030561,030562,030563,030564,030569,030571,030572,030579,030611,030612,030613,030614,030615,030616,030617,030619,030621,030622,030623,030624,030625,030626,030627,030629,030631,030632,030633,030634,030635,030636,030639,030691,030692,030693,030694,030695,030699,030710,030711,030712,030719,030721,030722,030729,030731,030732,030739,030741,030742,030743,030749,030751,030752,030759,030760,030771,030772,030779,030781,030782,030783,030784,030787,030788,030789,030791,030792,030799,030811,030812,030819,030821,030822,030829,030830,030890,030910,030990,040110,040120,040130,040140,040150,040210,040221,040229,040291,040299,040310,040320,040390,040410,040490,040500,040510,040520,040590,040610,040620,040630,040640,040690,040700,040711,040719,040721,040729,040790,040811,040819,040891,040899,040900,041000,041010,041090,050100,050210,050290,050300,050400,050510,050590,050610,050690,050710,050790,050800,050900,051000,051110,051191,051199,070110,070190,070200,070310,070320,070390,070410,070420,070490,070511,070519,070521,070529,070610,070690,070700,070810,070820,070890,070910,070920,070930,070940,070951,070952,070953,070954,070955,070956,070959,070960,070970,070990,070991,070992,070993,070999,071010,071021,071022,071029,071030,071040,071080,071090,071110,071120,071130,071140,071151,071159,071190,071210,071220,071230,071231,071232,071233,071234,071239,071290,071310,071320,071331,071332,071333,071334,071335,071339,071340,071350,071360,071390,071410,071420,071430,071440,071450,071490,080110,080111,080112,080119,080120,080121,080122,080130,080131,080132,080211,080212,080221,080222,080231,080232,080240,080241,080242,080250,080251,080252,080260,080261,080262,080270,080280,080290,080291,080292,080299,080300,080310,080390,080410,080420,080430,080440,080450,080510,080520,080521,080522,080529,080530,080540,080550,080590,080610,080620,080710,080711,080719,080720,080810,080820,080830,080840,080910,080920,080921,080929,080930,080940,081010,081020,081030,081040,081050,081060,081070,081090,081110,081120,081190,081210,081220,081290,081310,081320,081330,081340,081350,081400,090111,090112,090121,090122,090130,090140,090190,090210,090220,090230,090240,090300,090411,090412,090420,090421,090422,090500,090510,090520,090610,090611,090619,090620,090700,090710,090720,090810,090811,090812,090820,090821,090822,090830,090831,090832,090910,090920,090921,090922,090930,090931,090932,090940,090950,090961,090962,091010,091011,091012,091020,091030,091040,091050,091091,091099,110100,110210,110220,110230,110290,110311,110312,110313,110314,110319,110320,110321,110329,110411,110412,110419,110421,110422,110423,110429,110430,110510,110520,110610,110620,110630,110710,110720,110811,110812,110813,110814,110819,110820,110900,120100,120110,120190,120210,120220,120230,120241,120242,120300,120400,120500,120510,120590,120600,120710,120720,120721,120729,120730,120740,120750,120760,120770,120791,120792,120799,120810,120890,120910,120911,120919,120921,120922,120923,120924,120925,120926,120929,120930,120991,120999,121010,121020,121110,121120,121130,121140,121150,121160,121190,121210,121220,121221,121229,121230,121291,121292,121293,121294,121299,121300,121410,121490,150100,150110,150120,150190,150200,150210,150290,150300,150410,150420,150430,150500,150510,150590,150600,150710,150790,150810,150890,150910,150920,150930,150940,150990,151000,151010,151090,151110,151190,151211,151219,151221,151229,151311,151319,151321,151329,151410,151411,151419,151490,151491,151499,151511,151519,151521,151529,151530,151540,151550,151560,151590,151610,151620,151630,151710,151790,151800,151911,151912,151913,151919,151920,151930,152000,152010,152090,152110,152190,152200,160100,160210,160220,160231,160232,160239,160241,160242,160249,160250,160290,160300,160411,160412,160413,160414,160415,160416,160417,160418,160419,160420,160430,160431,160432,160510,160520,160521,160529,160530,160540,160551,160552,160553,160554,160555,160556,160557,160558,160559,160561,160562,160563,160569,160590,170111,170112,170113,170114,170191,170199,170210,170211,170219,170220,170230,170240,170250,170260,170290,170310,170390,170410,170490,190110,190120,190190,190211,190219,190220,190230,190240,190300,190410,190420,190430,190490,190510,190520,190530,190531,190532,190540,190590,200110,200120,200190,200210,200290,200310,200320,200390,200410,200490,200510,200520,200530,200540,200551,200559,200560,200570,200580,200590,200591,200599,200600,200710,200791,200799,200811,200819,200820,200830,200840,200850,200860,200870,200880,200891,200892,200893,200897,200899,200911,200912,200919,200920,200921,200929,200930,200931,200939,200940,200941,200949,200950,200960,200961,200969,200970,200971,200979,200980,200981,200989,200990,210110,210111,210112,210120,210130,210210,210220,210230,210310,210320,210330,210390,210410,210420,210500,210610,210690,220110,220190,220210,220290,220291,220299,220300,220410,220421,220422,220429,220430,220510,220590,220600,220710,220720,220810,220820,220830,220840,220850,220860,220870,220890,220900,230110,230120,230210,230220,230230,230240,230250,230310,230320,230330,230400,230500,230610,230620,230630,230640,230641,230649,230650,230660,230670,230690,230700,230800,230810,230890,230910,230990,250100,250200,250300,250310,250390,250410,250490,250510,250590,250610,250620,250621,250629,250700,250810,250820,250830,250840,250850,250860,250870,250900,251010,251020,251110,251120,251200,251310,251311,251319,251320,251321,251329,251400,251511,251512,251520,251611,251612,251620,251621,251622,251690,251710,251720,251730,251741,251749,251810,251820,251830,251910,251990,252010,252020,252100,252210,252220,252230,252310,252321,252329,252330,252390,252400,252410,252490,252510,252520,252530,252610,252620,252700,252800,252810,252890,252910,252921,252922,252930,253010,253020,253030,253040,253090,260111,260112,260120,260200,260300,260400,260500,260600,260700,260800,260900,261000,261100,261210,261220,261310,261390,261400,261510,261590,261610,261690,261710,261790,261800,261900,262011,262019,262020,262021,262029,262030,262040,262050,262060,262090,262091,262099,262100,262110,262190,270111,270112,270119,270120,270210,270220,270300,270400,270500,270600,270710,270720,270730,270740,270750,270760,270791,270799,270810,270820,270900,271000,271011,271012,271013,271014,271015,271016,271019,271020,271021,271022,271025,271026,271027,271029,271091,271093,271094,271095,271096,271099,271111,271112,271113,271114,271119,271121,271129,271210,271220,271290,271311,271312,271320,271390,271410,271490,271500,271600,320110,320120,320130,320190,320210,320290,320300,320411,320412,320413,320414,320415,320416,320417,320418,320419,320420,320490,320500,320610,320611,320619,320620,320630,320641,320642,320643,320649,320650,320710,320720,320730,320740,320810,320820,320890,320910,320990,321000,321100,321210,321290,321310,321390,321410,321490,321511,321519,321590,330111,330112,330113,330114,330119,330121,330122,330123,330124,330125,330126,330129,330130,330190,330210,330290,330300,330410,330420,330430,330491,330499,330510,330520,330530,330590,330610,330620,330690,330710,330720,330730,330741,330749,330790,340111,340119,340120,340130,340211,340212,340213,340219,340220,340231,340239,340241,340242,340249,340250,340290,340311,340319,340391,340399,340410,340420,340490,340510,340520,340530,340540,340590,340600,340700,390110,390120,390130,390140,390190,390210,390220,390230,390290,390311,390319,390320,390330,390390,390410,390421,390422,390430,390440,390450,390461,390469,390490,390511,390512,390519,390520,390521,390529,390530,390590,390591,390599,390610,390690,390710,390720,390721,390729,390730,390740,390750,390760,390761,390769,390770,390791,390799,390810,390890,390910,390920,390930,390931,390939,390940,390950,391000,391110,391120,391190,391211,391212,391220,391231,391239,391290,391310,391390,391400,391510,391520,391530,391590,391610,391620,391690,391710,391721,391722,391723,391729,391731,391732,391733,391739,391740,391810,391890,391910,391990,392010,392020,392030,392041,392042,392043,392049,392051,392059,392061,392062,392063,392069,392071,392072,392073,392079,392091,392092,392093,392094,392099,392111,392112,392113,392114,392119,392190,392210,392220,392290,392310,392321,392329,392330,392340,392350,392390,392410,392490,392510,392520,392530,392590,392610,392620,392630,392640,392690,400110,400121,400122,400129,400130,400211,400219,400220,400231,400239,400241,400249,400251,400259,400260,400270,400280,400291,400299,400300,400400,400510,400520,400591,400599,400610,400690,400700,400811,400819,400821,400829,400910,400911,400912,400920,400921,400922,400930,400931,400932,400940,400941,400942,400950,401010,401011,401012,401013,401019,401021,401022,401023,401024,401029,401031,401032,401033,401034,401035,401036,401039,401091,401099,401110,401120,401130,401140,401150,401161,401162,401163,401169,401170,401180,401190,401191,401192,401193,401194,401199,401210,401211,401212,401213,401219,401220,401290,401310,401320,401390,401410,401490,401511,401512,401519,401590,401610,401691,401692,401693,401694,401695,401699,401700,420100,420211,420212,420219,420221,420222,420229,420231,420232,420239,420291,420292,420299,420310,420321,420329,420330,420340,420400,420500,420600,420610,420690,440110,440111,440112,440121,440122,440130,440131,440132,440139,440140,440141,440149,440200,440210,440220,440290,440310,440311,440312,440320,440321,440322,440323,440324,440325,440326,440331,440332,440333,440334,440335,440341,440342,440349,440391,440392,440393,440394,440395,440396,440397,440398,440399,440410,440420,440500,440610,440611,440612,440690,440691,440692,440710,440711,440712,440713,440714,440719,440721,440722,440723,440724,440725,440726,440727,440728,440729,440791,440792,440793,440794,440795,440796,440797,440799,440810,440820,440831,440839,440890,440910,440920,440921,440922,440929,441010,441011,441012,441019,441021,441029,441031,441032,441033,441039,441090,441111,441112,441113,441114,441119,441121,441129,441131,441139,441191,441192,441193,441194,441199,441210,441211,441212,441213,441214,441219,441221,441222,441223,441229,441231,441232,441233,441234,441239,441241,441242,441249,441251,441252,441259,441291,441292,441293,441294,441299,441300,441400,441410,441490,441510,441520,441600,441700,441810,441811,441819,441820,441821,441829,441830,441840,441850,441860,441871,441872,441873,441874,441875,441879,441881,441882,441883,441889,441890,441891,441892,441899,441900,441911,441912,441919,441920,441990,442010,442011,442019,442090,442110,442120,442190,442191,442199,490110,490191,490199,490210,490290,490300,490400,490510,490520,490590,490591,490599,490600,490700,490810,490890,490900,491000,491110,491191,491199,540110,540120,540210,540211,540219,540220,540231,540232,540233,540234,540239,540241,540242,540243,540244,540245,540246,540247,540248,540249,540251,540252,540253,540259,540261,540262,540263,540269,540310,540320,540331,540332,540333,540339,540341,540342,540349,540410,540411,540412,540419,540490,540500,540600,540610,540620,540710,540720,540730,540741,540742,540743,540744,540751,540752,540753,540754,540760,540761,540769,540771,540772,540773,540774,540781,540782,540783,540784,540791,540792,540793,540794,540810,540821,540822,540823,540824,540831,540832,540833,540834,550110,550111,550119,550120,550130,550140,550190,550200,550210,550290,550310,550311,550319,550320,550330,550340,550390,550410,550490,550510,550520,550610,550620,550630,550640,550690,550700,550810,550820,550911,550912,550921,550922,550931,550932,550941,550942,550951,550952,550953,550959,550961,550962,550969,550991,550992,550999,551011,551012,551020,551030,551090,551110,551120,551130,551211,551219,551221,551229,551291,551299,551311,551312,551313,551319,551321,551322,551323,551329,551331,551332,551333,551339,551341,551342,551343,551349,551411,551412,551413,551419,551421,551422,551423,551429,551430,551431,551432,551433,551439,551441,551442,551443,551449,551511,551512,551513,551519,551521,551522,551529,551591,551592,551599,551611,551612,551613,551614,551621,551622,551623,551624,551631,551632,551633,551634,551641,551642,551643,551644,551691,551692,551693,551694,560110,560121,560122,560129,560130,560210,560221,560229,560290,560300,560311,560312,560313,560314,560391,560392,560393,560394,560410,560420,560490,560500,560600,560710,560721,560729,560730,560741,560749,560750,560790,560811,560819,560890,560900,580110,580121,580122,580123,580124,580125,580126,580127,580131,580132,580133,580134,580135,580136,580137,580190,580210,580211,580219,580220,580230,580300,580310,580390,580410,580421,580429,580430,580500,580610,580620,580631,580632,580639,580640,580710,580790,580810,580890,580900,581010,581091,581092,581099,581100,610110,610120,610130,610190,610210,610220,610230,610290,610310,610311,610312,610319,610321,610322,610323,610329,610331,610332,610333,610339,610341,610342,610343,610349,610411,610412,610413,610419,610421,610422,610423,610429,610431,610432,610433,610439,610441,610442,610443,610444,610449,610451,610452,610453,610459,610461,610462,610463,610469,610510,610520,610590,610610,610620,610690,610711,610712,610719,610721,610722,610729,610791,610792,610799,610811,610819,610821,610822,610829,610831,610832,610839,610891,610892,610899,610910,610990,611010,611011,611012,611019,611020,611030,611090,611110,611120,611130,611190,611211,611212,611219,611220,611231,611239,611241,611249,611300,611410,611420,611430,611490,611510,611511,611512,611519,611520,611521,611522,611529,611530,611591,611592,611593,611594,611595,611596,611599,611610,611691,611692,611693,611699,611710,611720,611780,611790,630110,630120,630130,630140,630190,630210,630221,630222,630229,630231,630232,630239,630240,630251,630252,630253,630259,630260,630291,630292,630293,630299,630311,630312,630319,630391,630392,630399,630411,630419,630420,630491,630492,630493,630499,630510,630520,630531,630532,630533,630539,630590,630611,630612,630619,630621,630622,630629,630630,630631,630639,630640,630641,630649,630690,630691,630699,630710,630720,630790,630800,630900,631010,631090,640110,640191,640192,640199,640211,640212,640219,640220,640230,640291,640299,640311,640312,640319,640320,640330,640340,640351,640359,640391,640399,640411,640419,640420,640510,640520,640590,640610,640620,640690,640691,640699,690100,690210,690220,690290,690310,690320,690390,690410,690490,690510,690590,690600,690710,690721,690722,690723,690730,690740,690790,690810,690890,690911,690912,690919,690990,691010,691090,691110,691190,691200,691310,691390,691410,691490,700100,700210,700220,700231,700232,700239,700311,700312,700319,700320,700330,700410,700420,700490,700510,700521,700529,700530,700600,700711,700719,700721,700729,700800,700910,700991,700992,701010,701020,701090,701091,701092,701093,701094,701110,701120,701190,701200,701310,701321,701322,701328,701329,701331,701332,701333,701337,701339,701341,701342,701349,701391,701399,701400,701510,701590,701610,701690,701710,701720,701790,701810,701820,701890,701910,701911,701912,701913,701914,701915,701919,701920,701931,701932,701939,701940,701951,701952,701959,701961,701962,701963,701964,701965,701966,701969,701971,701972,701973,701980,701990,702000,720110,720120,720130,720140,720150,720211,720219,720221,720229,720230,720241,720249,720250,720260,720270,720280,720291,720292,720293,720299,720310,720390,720410,720421,720429,720430,720441,720449,720450,720510,720521,720529,720610,720690,720711,720712,720719,720720,720810,720811,720812,720813,720814,720821,720822,720823,720824,720825,720826,720827,720831,720832,720833,720834,720835,720836,720837,720838,720839,720840,720841,720842,720843,720844,720845,720851,720852,720853,720854,720890,720911,720912,720913,720914,720915,720916,720917,720918,720921,720922,720923,720924,720925,720926,720927,720928,720931,720932,720933,720934,720941,720942,720943,720944,720990,721011,721012,721020,721030,721031,721039,721041,721049,721050,721060,721061,721069,721070,721090,721111,721112,721113,721114,721119,721121,721122,721123,721129,721130,721141,721149,721190,721210,721220,721221,721229,721230,721240,721250,721260,721310,721320,721331,721339,721341,721349,721350,721391,721399,721410,721420,721430,721440,721450,721460,721491,721499,721510,721520,721530,721540,721550,721590,721610,721621,721622,721631,721632,721633,721640,721650,721660,721661,721669,721690,721691,721699,721710,721711,721712,721713,721719,721720,721721,721722,721723,721729,721730,721731,721732,721733,721739,721790,721810,721890,721891,721899,721911,721912,721913,721914,721921,721922,721923,721924,721931,721932,721933,721934,721935,721990,722011,722012,722020,722090,722100,722210,722211,722219,722220,722230,722240,722300,722410,722490,722510,722511,722519,722520,722530,722540,722550,722590,722591,722592,722599,722610,722611,722619,722620,722691,722692,722693,722694,722699,722710,722720,722790,722810,722820,722830,722840,722850,722860,722870,722880,722910,722920,722990,730110,730120,730210,730220,730230,730240,730290,730300,730410,730411,730419,730420,730421,730422,730423,730424,730429,730431,730439,730441,730449,730451,730459,730490,730511,730512,730519,730520,730531,730539,730590,730610,730611,730619,730620,730621,730629,730630,730640,730650,730660,730661,730669,730690,730711,730719,730721,730722,730723,730729,730791,730792,730793,730799,730810,730820,730830,730840,730890,730900,731010,731021,731029,731100,731210,731290,731300,731411,731412,731413,731414,731419,731420,731430,731431,731439,731441,731442,731449,731450,731511,731512,731519,731520,731581,731582,731589,731590,731600,731700,731811,731812,731813,731814,731815,731816,731819,731821,731822,731823,731824,731829,731910,731920,731930,731940,731990,732010,732020,732090,732111,732112,732113,732119,732181,732182,732183,732189,732190,732211,732219,732290,732310,732391,732392,732393,732394,732399,732410,732421,732429,732490,732510,732591,732599,732611,732619,732620,732690,740100,740110,740120,740200,740311,740312,740313,740319,740321,740322,740323,740329,740400,740500,740610,740620,740710,740721,740722,740729,740811,740819,740821,740822,740829,740911,740919,740921,740929,740931,740939,740940,740990,741011,741012,741021,741022,741110,741121,741122,741129,741210,741220,741300,741410,741420,741490,741510,741521,741529,741531,741532,741533,741539,741600,741700,741810,741811,741819,741820,741910,741920,741980,741991,741999,760110,760120,760200,760310,760320,760410,760421,760429,760511,760519,760521,760529,760611,760612,760691,760692,760711,760719,760720,760810,760820,760900,761010,761090,761100,761210,761290,761300,761410,761490,761510,761511,761519,761520,761610,761690,761691,761699,790111,790112,790120,790200,790310,790390,790400,790500,790600,790700,790710,790790,820110,820120,820130,820140,82

In [14]:
gambia_exports_2023 =get_data_from_uncomtrade(reporter="270",partner=codes,data_date="2023",flowCode='X', frequency="A", hs_code=positive_top_5_items,hs_2_digit=False,hs_4_digit=False,hs_6_digit=True)

Final codes_string= 030110,030111,030119,030191,030192,030193,030194,030195,030199,030211,030212,030213,030214,030219,030221,030222,030223,030224,030229,030231,030232,030233,030234,030235,030236,030239,030240,030241,030242,030243,030244,030245,030246,030247,030249,030250,030251,030252,030253,030254,030255,030256,030259,030261,030262,030263,030264,030265,030266,030267,030268,030269,030270,030271,030272,030273,030274,030279,030281,030282,030283,030284,030285,030289,030290,030291,030292,030299,030310,030311,030312,030313,030314,030319,030321,030322,030323,030324,030325,030326,030329,030331,030332,030333,030334,030339,030341,030342,030343,030344,030345,030346,030349,030350,030351,030352,030353,030354,030355,030356,030357,030359,030360,030361,030362,030363,030364,030365,030366,030367,030368,030369,030371,030372,030373,030374,030375,030376,030377,030378,030379,030380,030381,030382,030383,030384,030389,030390,030391,030392,030399,030410,030411,030412,030419,030420,030421,030422,030429,030431,030432,030433,030439,030441,030442,030443,030444,030445,030446,030447,030448,030449,030451,030452,030453,030454,030455,030456,030457,030459,030461,030462,030463,030469,030471,030472,030473,030474,030475,030479,030481,030482,030483,030484,030485,030486,030487,030488,030489,030490,030491,030492,030493,030494,030495,030496,030497,030499,030510,030520,030530,030531,030532,030539,030541,030542,030543,030544,030549,030551,030552,030553,030554,030559,030561,030562,030563,030564,030569,030571,030572,030579,030611,030612,030613,030614,030615,030616,030617,030619,030621,030622,030623,030624,030625,030626,030627,030629,030631,030632,030633,030634,030635,030636,030639,030691,030692,030693,030694,030695,030699,030710,030711,030712,030719,030721,030722,030729,030731,030732,030739,030741,030742,030743,030749,030751,030752,030759,030760,030771,030772,030779,030781,030782,030783,030784,030787,030788,030789,030791,030792,030799,030811,030812,030819,030821,030822,030829,030830,030890,030910,030990,040110,040120,040130,040140,040150,040210,040221,040229,040291,040299,040310,040320,040390,040410,040490,040500,040510,040520,040590,040610,040620,040630,040640,040690,040700,040711,040719,040721,040729,040790,040811,040819,040891,040899,040900,041000,041010,041090,050100,050210,050290,050300,050400,050510,050590,050610,050690,050710,050790,050800,050900,051000,051110,051191,051199,070110,070190,070200,070310,070320,070390,070410,070420,070490,070511,070519,070521,070529,070610,070690,070700,070810,070820,070890,070910,070920,070930,070940,070951,070952,070953,070954,070955,070956,070959,070960,070970,070990,070991,070992,070993,070999,071010,071021,071022,071029,071030,071040,071080,071090,071110,071120,071130,071140,071151,071159,071190,071210,071220,071230,071231,071232,071233,071234,071239,071290,071310,071320,071331,071332,071333,071334,071335,071339,071340,071350,071360,071390,071410,071420,071430,071440,071450,071490,080110,080111,080112,080119,080120,080121,080122,080130,080131,080132,080211,080212,080221,080222,080231,080232,080240,080241,080242,080250,080251,080252,080260,080261,080262,080270,080280,080290,080291,080292,080299,080300,080310,080390,080410,080420,080430,080440,080450,080510,080520,080521,080522,080529,080530,080540,080550,080590,080610,080620,080710,080711,080719,080720,080810,080820,080830,080840,080910,080920,080921,080929,080930,080940,081010,081020,081030,081040,081050,081060,081070,081090,081110,081120,081190,081210,081220,081290,081310,081320,081330,081340,081350,081400,090111,090112,090121,090122,090130,090140,090190,090210,090220,090230,090240,090300,090411,090412,090420,090421,090422,090500,090510,090520,090610,090611,090619,090620,090700,090710,090720,090810,090811,090812,090820,090821,090822,090830,090831,090832,090910,090920,090921,090922,090930,090931,090932,090940,090950,090961,090962,091010,091011,091012,091020,091030,091040,091050,091091,091099,110100,110210,110220,110230,110290,110311,110312,110313,110314,110319,110320,110321,110329,110411,110412,110419,110421,110422,110423,110429,110430,110510,110520,110610,110620,110630,110710,110720,110811,110812,110813,110814,110819,110820,110900,120100,120110,120190,120210,120220,120230,120241,120242,120300,120400,120500,120510,120590,120600,120710,120720,120721,120729,120730,120740,120750,120760,120770,120791,120792,120799,120810,120890,120910,120911,120919,120921,120922,120923,120924,120925,120926,120929,120930,120991,120999,121010,121020,121110,121120,121130,121140,121150,121160,121190,121210,121220,121221,121229,121230,121291,121292,121293,121294,121299,121300,121410,121490,150100,150110,150120,150190,150200,150210,150290,150300,150410,150420,150430,150500,150510,150590,150600,150710,150790,150810,150890,150910,150920,150930,150940,150990,151000,151010,151090,151110,151190,151211,151219,151221,151229,151311,151319,151321,151329,151410,151411,151419,151490,151491,151499,151511,151519,151521,151529,151530,151540,151550,151560,151590,151610,151620,151630,151710,151790,151800,151911,151912,151913,151919,151920,151930,152000,152010,152090,152110,152190,152200,160100,160210,160220,160231,160232,160239,160241,160242,160249,160250,160290,160300,160411,160412,160413,160414,160415,160416,160417,160418,160419,160420,160430,160431,160432,160510,160520,160521,160529,160530,160540,160551,160552,160553,160554,160555,160556,160557,160558,160559,160561,160562,160563,160569,160590,170111,170112,170113,170114,170191,170199,170210,170211,170219,170220,170230,170240,170250,170260,170290,170310,170390,170410,170490,190110,190120,190190,190211,190219,190220,190230,190240,190300,190410,190420,190430,190490,190510,190520,190530,190531,190532,190540,190590,200110,200120,200190,200210,200290,200310,200320,200390,200410,200490,200510,200520,200530,200540,200551,200559,200560,200570,200580,200590,200591,200599,200600,200710,200791,200799,200811,200819,200820,200830,200840,200850,200860,200870,200880,200891,200892,200893,200897,200899,200911,200912,200919,200920,200921,200929,200930,200931,200939,200940,200941,200949,200950,200960,200961,200969,200970,200971,200979,200980,200981,200989,200990,210110,210111,210112,210120,210130,210210,210220,210230,210310,210320,210330,210390,210410,210420,210500,210610,210690,220110,220190,220210,220290,220291,220299,220300,220410,220421,220422,220429,220430,220510,220590,220600,220710,220720,220810,220820,220830,220840,220850,220860,220870,220890,220900,230110,230120,230210,230220,230230,230240,230250,230310,230320,230330,230400,230500,230610,230620,230630,230640,230641,230649,230650,230660,230670,230690,230700,230800,230810,230890,230910,230990,250100,250200,250300,250310,250390,250410,250490,250510,250590,250610,250620,250621,250629,250700,250810,250820,250830,250840,250850,250860,250870,250900,251010,251020,251110,251120,251200,251310,251311,251319,251320,251321,251329,251400,251511,251512,251520,251611,251612,251620,251621,251622,251690,251710,251720,251730,251741,251749,251810,251820,251830,251910,251990,252010,252020,252100,252210,252220,252230,252310,252321,252329,252330,252390,252400,252410,252490,252510,252520,252530,252610,252620,252700,252800,252810,252890,252910,252921,252922,252930,253010,253020,253030,253040,253090,260111,260112,260120,260200,260300,260400,260500,260600,260700,260800,260900,261000,261100,261210,261220,261310,261390,261400,261510,261590,261610,261690,261710,261790,261800,261900,262011,262019,262020,262021,262029,262030,262040,262050,262060,262090,262091,262099,262100,262110,262190,270111,270112,270119,270120,270210,270220,270300,270400,270500,270600,270710,270720,270730,270740,270750,270760,270791,270799,270810,270820,270900,271000,271011,271012,271013,271014,271015,271016,271019,271020,271021,271022,271025,271026,271027,271029,271091,271093,271094,271095,271096,271099,271111,271112,271113,271114,271119,271121,271129,271210,271220,271290,271311,271312,271320,271390,271410,271490,271500,271600,320110,320120,320130,320190,320210,320290,320300,320411,320412,320413,320414,320415,320416,320417,320418,320419,320420,320490,320500,320610,320611,320619,320620,320630,320641,320642,320643,320649,320650,320710,320720,320730,320740,320810,320820,320890,320910,320990,321000,321100,321210,321290,321310,321390,321410,321490,321511,321519,321590,330111,330112,330113,330114,330119,330121,330122,330123,330124,330125,330126,330129,330130,330190,330210,330290,330300,330410,330420,330430,330491,330499,330510,330520,330530,330590,330610,330620,330690,330710,330720,330730,330741,330749,330790,340111,340119,340120,340130,340211,340212,340213,340219,340220,340231,340239,340241,340242,340249,340250,340290,340311,340319,340391,340399,340410,340420,340490,340510,340520,340530,340540,340590,340600,340700,390110,390120,390130,390140,390190,390210,390220,390230,390290,390311,390319,390320,390330,390390,390410,390421,390422,390430,390440,390450,390461,390469,390490,390511,390512,390519,390520,390521,390529,390530,390590,390591,390599,390610,390690,390710,390720,390721,390729,390730,390740,390750,390760,390761,390769,390770,390791,390799,390810,390890,390910,390920,390930,390931,390939,390940,390950,391000,391110,391120,391190,391211,391212,391220,391231,391239,391290,391310,391390,391400,391510,391520,391530,391590,391610,391620,391690,391710,391721,391722,391723,391729,391731,391732,391733,391739,391740,391810,391890,391910,391990,392010,392020,392030,392041,392042,392043,392049,392051,392059,392061,392062,392063,392069,392071,392072,392073,392079,392091,392092,392093,392094,392099,392111,392112,392113,392114,392119,392190,392210,392220,392290,392310,392321,392329,392330,392340,392350,392390,392410,392490,392510,392520,392530,392590,392610,392620,392630,392640,392690,400110,400121,400122,400129,400130,400211,400219,400220,400231,400239,400241,400249,400251,400259,400260,400270,400280,400291,400299,400300,400400,400510,400520,400591,400599,400610,400690,400700,400811,400819,400821,400829,400910,400911,400912,400920,400921,400922,400930,400931,400932,400940,400941,400942,400950,401010,401011,401012,401013,401019,401021,401022,401023,401024,401029,401031,401032,401033,401034,401035,401036,401039,401091,401099,401110,401120,401130,401140,401150,401161,401162,401163,401169,401170,401180,401190,401191,401192,401193,401194,401199,401210,401211,401212,401213,401219,401220,401290,401310,401320,401390,401410,401490,401511,401512,401519,401590,401610,401691,401692,401693,401694,401695,401699,401700,420100,420211,420212,420219,420221,420222,420229,420231,420232,420239,420291,420292,420299,420310,420321,420329,420330,420340,420400,420500,420600,420610,420690,440110,440111,440112,440121,440122,440130,440131,440132,440139,440140,440141,440149,440200,440210,440220,440290,440310,440311,440312,440320,440321,440322,440323,440324,440325,440326,440331,440332,440333,440334,440335,440341,440342,440349,440391,440392,440393,440394,440395,440396,440397,440398,440399,440410,440420,440500,440610,440611,440612,440690,440691,440692,440710,440711,440712,440713,440714,440719,440721,440722,440723,440724,440725,440726,440727,440728,440729,440791,440792,440793,440794,440795,440796,440797,440799,440810,440820,440831,440839,440890,440910,440920,440921,440922,440929,441010,441011,441012,441019,441021,441029,441031,441032,441033,441039,441090,441111,441112,441113,441114,441119,441121,441129,441131,441139,441191,441192,441193,441194,441199,441210,441211,441212,441213,441214,441219,441221,441222,441223,441229,441231,441232,441233,441234,441239,441241,441242,441249,441251,441252,441259,441291,441292,441293,441294,441299,441300,441400,441410,441490,441510,441520,441600,441700,441810,441811,441819,441820,441821,441829,441830,441840,441850,441860,441871,441872,441873,441874,441875,441879,441881,441882,441883,441889,441890,441891,441892,441899,441900,441911,441912,441919,441920,441990,442010,442011,442019,442090,442110,442120,442190,442191,442199,490110,490191,490199,490210,490290,490300,490400,490510,490520,490590,490591,490599,490600,490700,490810,490890,490900,491000,491110,491191,491199,540110,540120,540210,540211,540219,540220,540231,540232,540233,540234,540239,540241,540242,540243,540244,540245,540246,540247,540248,540249,540251,540252,540253,540259,540261,540262,540263,540269,540310,540320,540331,540332,540333,540339,540341,540342,540349,540410,540411,540412,540419,540490,540500,540600,540610,540620,540710,540720,540730,540741,540742,540743,540744,540751,540752,540753,540754,540760,540761,540769,540771,540772,540773,540774,540781,540782,540783,540784,540791,540792,540793,540794,540810,540821,540822,540823,540824,540831,540832,540833,540834,550110,550111,550119,550120,550130,550140,550190,550200,550210,550290,550310,550311,550319,550320,550330,550340,550390,550410,550490,550510,550520,550610,550620,550630,550640,550690,550700,550810,550820,550911,550912,550921,550922,550931,550932,550941,550942,550951,550952,550953,550959,550961,550962,550969,550991,550992,550999,551011,551012,551020,551030,551090,551110,551120,551130,551211,551219,551221,551229,551291,551299,551311,551312,551313,551319,551321,551322,551323,551329,551331,551332,551333,551339,551341,551342,551343,551349,551411,551412,551413,551419,551421,551422,551423,551429,551430,551431,551432,551433,551439,551441,551442,551443,551449,551511,551512,551513,551519,551521,551522,551529,551591,551592,551599,551611,551612,551613,551614,551621,551622,551623,551624,551631,551632,551633,551634,551641,551642,551643,551644,551691,551692,551693,551694,560110,560121,560122,560129,560130,560210,560221,560229,560290,560300,560311,560312,560313,560314,560391,560392,560393,560394,560410,560420,560490,560500,560600,560710,560721,560729,560730,560741,560749,560750,560790,560811,560819,560890,560900,580110,580121,580122,580123,580124,580125,580126,580127,580131,580132,580133,580134,580135,580136,580137,580190,580210,580211,580219,580220,580230,580300,580310,580390,580410,580421,580429,580430,580500,580610,580620,580631,580632,580639,580640,580710,580790,580810,580890,580900,581010,581091,581092,581099,581100,610110,610120,610130,610190,610210,610220,610230,610290,610310,610311,610312,610319,610321,610322,610323,610329,610331,610332,610333,610339,610341,610342,610343,610349,610411,610412,610413,610419,610421,610422,610423,610429,610431,610432,610433,610439,610441,610442,610443,610444,610449,610451,610452,610453,610459,610461,610462,610463,610469,610510,610520,610590,610610,610620,610690,610711,610712,610719,610721,610722,610729,610791,610792,610799,610811,610819,610821,610822,610829,610831,610832,610839,610891,610892,610899,610910,610990,611010,611011,611012,611019,611020,611030,611090,611110,611120,611130,611190,611211,611212,611219,611220,611231,611239,611241,611249,611300,611410,611420,611430,611490,611510,611511,611512,611519,611520,611521,611522,611529,611530,611591,611592,611593,611594,611595,611596,611599,611610,611691,611692,611693,611699,611710,611720,611780,611790,630110,630120,630130,630140,630190,630210,630221,630222,630229,630231,630232,630239,630240,630251,630252,630253,630259,630260,630291,630292,630293,630299,630311,630312,630319,630391,630392,630399,630411,630419,630420,630491,630492,630493,630499,630510,630520,630531,630532,630533,630539,630590,630611,630612,630619,630621,630622,630629,630630,630631,630639,630640,630641,630649,630690,630691,630699,630710,630720,630790,630800,630900,631010,631090,640110,640191,640192,640199,640211,640212,640219,640220,640230,640291,640299,640311,640312,640319,640320,640330,640340,640351,640359,640391,640399,640411,640419,640420,640510,640520,640590,640610,640620,640690,640691,640699,690100,690210,690220,690290,690310,690320,690390,690410,690490,690510,690590,690600,690710,690721,690722,690723,690730,690740,690790,690810,690890,690911,690912,690919,690990,691010,691090,691110,691190,691200,691310,691390,691410,691490,700100,700210,700220,700231,700232,700239,700311,700312,700319,700320,700330,700410,700420,700490,700510,700521,700529,700530,700600,700711,700719,700721,700729,700800,700910,700991,700992,701010,701020,701090,701091,701092,701093,701094,701110,701120,701190,701200,701310,701321,701322,701328,701329,701331,701332,701333,701337,701339,701341,701342,701349,701391,701399,701400,701510,701590,701610,701690,701710,701720,701790,701810,701820,701890,701910,701911,701912,701913,701914,701915,701919,701920,701931,701932,701939,701940,701951,701952,701959,701961,701962,701963,701964,701965,701966,701969,701971,701972,701973,701980,701990,702000,720110,720120,720130,720140,720150,720211,720219,720221,720229,720230,720241,720249,720250,720260,720270,720280,720291,720292,720293,720299,720310,720390,720410,720421,720429,720430,720441,720449,720450,720510,720521,720529,720610,720690,720711,720712,720719,720720,720810,720811,720812,720813,720814,720821,720822,720823,720824,720825,720826,720827,720831,720832,720833,720834,720835,720836,720837,720838,720839,720840,720841,720842,720843,720844,720845,720851,720852,720853,720854,720890,720911,720912,720913,720914,720915,720916,720917,720918,720921,720922,720923,720924,720925,720926,720927,720928,720931,720932,720933,720934,720941,720942,720943,720944,720990,721011,721012,721020,721030,721031,721039,721041,721049,721050,721060,721061,721069,721070,721090,721111,721112,721113,721114,721119,721121,721122,721123,721129,721130,721141,721149,721190,721210,721220,721221,721229,721230,721240,721250,721260,721310,721320,721331,721339,721341,721349,721350,721391,721399,721410,721420,721430,721440,721450,721460,721491,721499,721510,721520,721530,721540,721550,721590,721610,721621,721622,721631,721632,721633,721640,721650,721660,721661,721669,721690,721691,721699,721710,721711,721712,721713,721719,721720,721721,721722,721723,721729,721730,721731,721732,721733,721739,721790,721810,721890,721891,721899,721911,721912,721913,721914,721921,721922,721923,721924,721931,721932,721933,721934,721935,721990,722011,722012,722020,722090,722100,722210,722211,722219,722220,722230,722240,722300,722410,722490,722510,722511,722519,722520,722530,722540,722550,722590,722591,722592,722599,722610,722611,722619,722620,722691,722692,722693,722694,722699,722710,722720,722790,722810,722820,722830,722840,722850,722860,722870,722880,722910,722920,722990,730110,730120,730210,730220,730230,730240,730290,730300,730410,730411,730419,730420,730421,730422,730423,730424,730429,730431,730439,730441,730449,730451,730459,730490,730511,730512,730519,730520,730531,730539,730590,730610,730611,730619,730620,730621,730629,730630,730640,730650,730660,730661,730669,730690,730711,730719,730721,730722,730723,730729,730791,730792,730793,730799,730810,730820,730830,730840,730890,730900,731010,731021,731029,731100,731210,731290,731300,731411,731412,731413,731414,731419,731420,731430,731431,731439,731441,731442,731449,731450,731511,731512,731519,731520,731581,731582,731589,731590,731600,731700,731811,731812,731813,731814,731815,731816,731819,731821,731822,731823,731824,731829,731910,731920,731930,731940,731990,732010,732020,732090,732111,732112,732113,732119,732181,732182,732183,732189,732190,732211,732219,732290,732310,732391,732392,732393,732394,732399,732410,732421,732429,732490,732510,732591,732599,732611,732619,732620,732690,740100,740110,740120,740200,740311,740312,740313,740319,740321,740322,740323,740329,740400,740500,740610,740620,740710,740721,740722,740729,740811,740819,740821,740822,740829,740911,740919,740921,740929,740931,740939,740940,740990,741011,741012,741021,741022,741110,741121,741122,741129,741210,741220,741300,741410,741420,741490,741510,741521,741529,741531,741532,741533,741539,741600,741700,741810,741811,741819,741820,741910,741920,741980,741991,741999,760110,760120,760200,760310,760320,760410,760421,760429,760511,760519,760521,760529,760611,760612,760691,760692,760711,760719,760720,760810,760820,760900,761010,761090,761100,761210,761290,761300,761410,761490,761510,761511,761519,761520,761610,761690,761691,761699,790111,790112,790120,790200,790310,790390,790400,790500,790600,790700,790710,790790,820110,820120,820130,820140,82

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4528\443933539.py:156: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_dataframe=pd.concat([final_dataframe,mydf])

In [15]:
gambia_exports_2023

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,flowDesc,partnerCode,partnerISO,partnerDesc,partner2Code,partner2ISO,partner2Desc,classificationCode,classificationSearchCode,isOriginalClassification,cmdCode,cmdDesc,aggrLevel,isLeaf,customsCode,customsDesc,mosCode,motCode,motDesc,qtyUnitCode,qtyUnitAbbr,qty,isQtyEstimated,altQtyUnitCode,altQtyUnitAbbr,altQty,isAltQtyEstimated,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20230101,2023,52,2023,270,GMB,Gambia,X,Export,410,KOR,Rep. of Korea,0,W00,World,H6,HS,True,030319,"Fish; frozen, salmonidae, n.e.c. in item no. 0...",6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,20800.0,False,8,kg,20800.0,False,20800.0,False,0.0,False,None,13372.160,13372.160,0,True,False
1,C,A,20230101,2023,52,2023,270,GMB,Gambia,X,Export,410,KOR,Rep. of Korea,0,W00,World,H6,HS,True,030223,"Fish; fresh or chilled, sole (Solea spp.), exc...",6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,333361.0,False,8,kg,333361.0,False,333361.0,False,0.0,False,None,231927.573,231927.573,0,True,False
2,C,A,20230101,2023,52,2023,270,GMB,Gambia,X,Export,410,KOR,Rep. of Korea,0,W00,World,H6,HS,True,030279,"Fish; fresh or chilled, Nile perch (Lates nilo...",6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,240406.0,False,8,kg,240406.0,False,240406.0,False,0.0,False,None,150286.308,150286.308,0,True,False
3,C,A,20230101,2023,52,2023,270,GMB,Gambia,X,Export,410,KOR,Rep. of Korea,0,W00,World,H6,HS,True,030312,"Fish; frozen, Pacific salmon (Oncorhynchus gor...",6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,21600.0,False,8,kg,21600.0,False,21600.0,False,0.0,False,None,16702.663,16702.663,0,True,False
4,C,A,20230101,2023,52,2023,270,GMB,Gambia,X,Export,408,PRK,Dem. People's Rep. of Korea,0,W00,World,H6,HS,True,030323,"Fish; frozen, tilapias (Oreochromis spp.), exc...",6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,24500.0,False,8,kg,24500.0,False,24500.0,False,0.0,False,None,6428.627,6428.627,0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,C,A,20230101,2023,52,2023,270,GMB,Gambia,X,Export,466,MLI,Mali,0,W00,World,H6,HS,True,940490,Bedding and similar furnishing articles; n.e.c...,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,284.0,False,8,kg,284.0,False,284.0,False,0.0,False,None,2221.928,2221.928,0,True,False
215,C,A,20230101,2023,52,2023,270,GMB,Gambia,X,Export,72,BWA,Botswana,0,W00,World,H6,HS,True,940529,"Luminaires and light fittings; electric, table...",6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,110.0,False,8,kg,110.0,False,110.0,False,0.0,False,None,98.057,98.057,0,True,False
216,C,A,20230101,2023,52,2023,270,GMB,Gambia,X,Export,686,SEN,Senegal,0,W00,World,H6,HS,True,940690,"Buildings; prefabricated, not of wood",6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,196000.0,False,8,kg,196000.0,False,196000.0,False,0.0,False,None,56316.759,56316.759,0,True,False
217,C,A,20230101,2023,52,2023,270,GMB,Gambia,X,Export,694,SLE,Sierra Leone,0,W00,World,H6,HS,True,961620,Powder puffs and pads; for the application of ...,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,8058.0,False,8,kg,8058.0,False,8058.0,False,0.0,False,None,8326.435,8326.435,0,True,False
218,C,A,20230101,2023,52,2023,270,GMB,Gambia,X,Export,686,SEN,Senegal,0,W00,World,H6,HS,True,961900,"Sanitary towels (pads) and tampons, napkins (d...",6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,25500.0,False,8,kg,25500.0,False,25500.0,False,0.0,False,None,9112.919,9112.919,0,True,False

In [16]:
# filter out the most important variables
gambia_exports_2022 = gambia_exports_2022[['refYear','reporterDesc','partnerDesc','partnerISO','cmdCode', 'fobvalue']]
gambia_exports_2023 = gambia_exports_2023[['refYear','reporterDesc','partnerDesc','partnerISO','cmdCode', 'fobvalue']]

In [17]:
gambia_exports_2022.head()

   refYear reporterDesc partnerDesc partnerISO cmdCode    fobvalue
0     2022       Gambia     Belgium        BEL  030279   17560.648
1     2022       Gambia      Brazil        BRA  030354   85733.718
2     2022       Gambia      Cyprus        CYP  030279   21569.353
3     2022       Gambia       Benin        BEN  030355    7930.021
4     2022       Gambia       Italy        ITA  030279  557331.537

In [18]:
total_exports_2022 = gambia_exports_2022['fobvalue'].sum()
print(f"Total export value for the year 2022: {total_exports_2022}")

Total export value for the year 2022: 54553080.888000004

In [19]:
print(gambia_exports_2022['cmdCode'].nunique())
print(gambia_exports_2022['partnerDesc'].nunique())

162
46

In [20]:
gambia_exports_2023.head()

,refYear,reporterDesc,partnerDesc,partnerISO,cmdCode,fobvalue
0,2023,Gambia,Rep. of Korea,KOR,030319,13372.160
1,2023,Gambia,Rep. of Korea,KOR,030223,231927.573
2,2023,Gambia,Rep. of Korea,KOR,030279,150286.308
3,2023,Gambia,Rep. of Korea,KOR,030312,16702.663
4,2023,Gambia,Dem. People's Rep. of Korea,PRK,030323,6428.627

In [21]:
print(gambia_exports_2023['cmdCode'].nunique())
print(gambia_exports_2023['partnerDesc'].nunique())

130
50

In [22]:
total_exports_2023 = gambia_exports_2023['fobvalue'].sum()
print(f"Total export value for the year 2023: {total_exports_2023}")

Total export value for the year 2023: 83355633.70699999

In [23]:
# export index
index_df = pd.read_csv('/content/drive/MyDrive/Trade project data/usa_data/d7f111f0-1329-4004-a6dc-a355f2385ec2_Data.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Trade project data/usa_data/d7f111f0-1329-4004-a6dc-a355f2385ec2_Data.csv'

In [ ]:
# refine the dataframe
index_df.rename(columns={'Country Name': 'partnerDesc', 'Country Code': 'partnerISO', '2022 [YR2022]': 'index'}, inplace=True)

In [ ]:
index_df= index_df[['partnerISO', 'index']]

In [ ]:
constant_df = pd.merge(partner_export_2022, index_df, on=['partnerISO'], how='left')

In [ ]:
constant_df['index'] = constant_df['index'].replace('..', '100')
# fill null value with 100
constant_df['index'] = constant_df['index'].fillna(100)

In [ ]:
constant_df['index'] = pd.to_numeric(constant_df['index'], errors='coerce')
constant_df['constant_usd'] = constant_df['fobvalue'] / (constant_df['index']) * 100

In [ ]:
constant_df.head()
print(constant_df.shape)

(220, 5)

In [ ]:
constant_df.isna().sum()

partnerDesc     0
partnerISO      0
fobvalue        0
index           0
constant_usd    0
dtype: int64

In [ ]:
# print the null values
print(constant_df[constant_df.isna().any(axis=1)])

                   partnerDesc partnerISO      fobvalue  index  constant_usd
5                     Anguilla        AIA  5.712335e+06    NaN           NaN
26      Br. Indian Ocean Terr.        IOT  3.921630e+05    NaN           NaN
44              Christmas Isds        CXR  8.662690e+05    NaN           NaN
45                  Cocos Isds        CCK  1.342609e+06    NaN           NaN
49                   Cook Isds        COK  9.693480e+05    NaN           NaN
72    Falkland Isds (Malvinas)        FLK  3.135775e+07    NaN           NaN
75   Fr. South Antarctic Terr.        ATF  8.535300e+04    NaN           NaN
130                 Montserrat        MSR  1.485528e+06    NaN           NaN
143                       Niue        NIU  2.627450e+06    NaN           NaN
144               Norfolk Isds        NFK  2.711940e+05    NaN           NaN
148            Other Asia, nes        S19  9.184460e+10    NaN           NaN
156                   Pitcairn        PCN  5.066610e+05    NaN           NaN
165               Saint Helena        SHN  2.157058e+07    NaN           NaN
168  Saint Pierre and Miquelon        SPM  1.841100e+04    NaN           NaN
198                    Tokelau        TKL  2.203210e+05    NaN           NaN
216     Wallis and Futuna Isds        WLF  1.079010e+05    NaN           NaN

In [ ]:
# calculate the total import value
total_imports_2022 = constant_df['constant_usd'].sum()
print(f"Total adjusted import value for the year 2022: {total_imports_2022}")

Total adjusted import value for the year 2022: 2380100036881.688

# services data

In [ ]:
services_df = pd.read_csv('/content/drive/MyDrive/Trade project data/usa_data/Commercial Services 7.31.2024.csv')

In [ ]:
# slice dataframe
usa_services = services_df[services_df['REPORTER CODE'] == 'US']
sorted_usa_services = usa_services[usa_services['FLOW'] == 'Imports'].sort_values('FLOW')

In [ ]:
# sort by specif year
services_df_2022 = sorted_usa_services[sorted_usa_services.YEAR == 2022]

In [ ]:
services_df_2022.head()

,FLOW,INDICATOR_CODE,REPORTER CODE,PARTNER CODE,REPORTER_COUNTRY_CODE,PARTNER_COUNTRY_CODE,REPORTING ECONOMY,PARTNER ECONOMY,SECTOR,YEAR,VALUE,UNIT
42219,Imports,SOX1,US,WL,RC840,SA000,United States of America,World,Other commercial services,2022,406552.0,Million US dollar
34676,Imports,S,US,WL,RC840,SA000,United States of America,World,Memo item: Total services,2022,713886.0,Million US dollar
49747,Imports,SC,US,WL,RC840,SA000,United States of America,World,Transport,2022,157711.0,Million US dollar
26964,Imports,SPX1,US,WL,RC840,SA000,United States of America,World,Memo item: Other services,2022,432099.0,Million US dollar
7287,Imports,SOX,US,WL,RC840,SA000,United States of America,World,Commercial services,2022,688339.0,Million US dollar

From the above dataframe get the Total services from sector column